examples/loop_mode.rs, examples/multi_window.rs, examples/simple_window.rs, examples/template.rs, src/app.rs, src/event.rs, src/lib.rs
This addresses and closes #5.
The examples have been updated and currently do a glob import e.g.
```rust
use nannou::event::SimpleWindowEvent::*;
```
However this will probably get removed soon in favour of adding these
variants to the prelude (see #10).
=> Add SimpleWindowEvent type for easier matching on window events

examples/loop_mode.rs, examples/multi_window.rs, examples/simple_window.rs, examples/template.rs, src/lib.rs, src/prelude.rs
This should simplify the process of kicking off a project with nannou.
At the moment I've just picked a few items which are already showing up
often in the examples. I don't have a particular rule in mind yet for
the kinds of items that should/shouldn't be added to the prelude. Maybe
we can come up with a set of rules for this, but for now I'm sure we
should be able to pick these pretty intuitively.
I guess this can be thought of as a more conservative `#include
ofMain.h` or Processing's list of auto-included items and keywords.
This closes #10.
=> Add a prelude module to remove common boilerplate from projects

examples/loop_mode.rs, examples/multi_window.rs, examples/simple_window.rs, examples/template.rs, src/event.rs, src/lib.rs
I think this makes a bit more sense semantically, rather than just
delivering a meaningless `Other` variant for every raw event that cannot
be interpreted as a `SimpleWindowEvent`.
This also improves the `simple_window` example where we print out each
emitted `SimpleWindowEvent`, as we no longer have `Other` spammed
between all the events that actually mean something.
There is a slight trade-off here in that the pattern matching is not
*quite* as simple as it was originally, however I think what's actually
going on should hopefully still be pretty obvious?
cc @freesig @JoshuaBatty
This also adds some more docs to the event conversion functions and fixes a bug in the `from_glutin_event` function where nannou used to `panic!` when receiving a `Closed` event.
Edit: this also makes the …
=> Remove `Other` variant from `SimpleWindowEvent` in favour of `Option`.

README.md, examples/loop_mode.rs, examples/multi_window.rs, examples/simple_window.rs, src/app.rs, src/event.rs, src/lib.rs, src/window.rs
Also fills out the `window::Builder` API to wrap the
`glutin::ContextBuilder` and `glutin::WindowBuilder` methods.
Updates the examples to use the `.with_title` method to display more
relevant titles.
`App` also now exposes a `window` method which can be used for borrowing the window at the given `window::Id`.
Closes #31
=> Add `Window` API with wrappers for glium and glutin methods

src/event.rs, src/lib.rs, src/ui.rs
This gives the user the option of taking back ownership of their `Model` on application exit (this can be useful for joining threads, triggering destructors in a certain order, etc).
=> Add optional exit function for consuming model on application exit

src/audio/stream/mod.rs, src/audio/stream/output.rs
This allows for a much more expressive audio update API as the compiler
now knows that audio model updates will only ever be called once. This
allows users to move non-Copy and non-Clone types into update closures.
Rust currently does not allow calling a `Box<FnOnce>` as the `FnOnce`
trait's `call` method takes `self` by value. To get around this, we move
the `FnOnce` closure into a `FnMut` closure on the stack before `Box`ing
it and sending it to the audio thread. We solve the ownership conflicts
between the `FnOnce` and `FnMut` functions by first moving the `FnOnce`
into an `Option` and calling `take()` within the `FnMut` closure,
ensuring that the type system knows that the `FnOnce` closure still only
gets called once.
=> Change audio::stream::Output::send API to take FnOnce instead of FnMut

examples/simple_audio.rs, src/app.rs, src/audio/stream/output.rs
Rather than having each new voice attempt to `run` the
`cpal::EventLoop`, we now run the `cpal::EventLoop` when the first voice
is created and use a `LoopContext` to handle multiple voices.
It also ensures that the `audio::stream::Output` handle can be `Clone`d
and sent to multiple threads.
=> Modify audio backend to properly handle multiple voices

src/audio/mod.rs, src/audio/stream/output.rs
This changes the audio output stream building process to pick more
reasonable defaults when certain parameters were not specified.
If no number of channels were specified, nannou will now attempt to use
all available output channels on the device.
If the target sample format happens to have an associated
`cpal::SampleFormat` that can be used for setting up a stream, nannou
will now first attempt to use a stream format with this matching sample
format to avoid the need for sample format conversions. If there are no
matching stream formats for the given sample format, nannou will fall
back to doing the conversion.
=> Make nannou smarter about audio output stream format defaults

src/geom/ellipse.rs, src/geom/mod.rs, src/geom/polygon.rs, src/geom/quad.rs, src/geom/range.rs, src/geom/rect.rs, src/geom/tri.rs, src/lib.rs, src/math.rs
The `geom` module provides efficient functions for describing primitives
via constructs that are commonly useful for graphical representations
such as sequences of points and triangles.
Also adds some more utility functions to the `math` module.
Should be able to use `geom` stuff as a foundation for a graphics API.
=>  Add `geom` module. Includes basic 2D primitives (besides lines/text). 

src/app.rs, src/event.rs, src/lib.rs, src/state.rs
Only `Mouse` and `Window` state tracking is implemented so far.
Tracked mouse state includes mouse position, window in focus and pressed buttons.
Tracked window state includes width, height, ID and hidpi_factor of window currently in focus.
Tracked keyboard state includes a set of pressed keys and the state of each of the modifier keys.
**Usage Examples**
Mouse
```
let x = app.mouse.x;
if app.mouse.buttons.left().is_down() {
// do something
}
let p = app.mouse.position();
```
Window
```
let w = app.window.width;
if app.window.id == my_window {
// do something
}
let size = app.window.size();
```
Keyboard
```
if app.keys.mods.ctrl {
// do something
}
if app.keys.down.contains(&Key::Space) || app.keys.down.contains(&Key::Enter) {
// do something if space or enter is down
}
```
Closes #53. …
=>  Add `state` module for tracking mouse, keyboard and window state.

src/math.rs, src/prelude.rs
Closes #56.
We can now make points using `pt2(x, y)`, `pt3(x, y, z)`, `vec3(x, y, z)`, etc, each of which are provided via the prelude.
cc @JoshuaBatty.
=> Expose helper Vector and Point constructors in prelude

Cargo.toml, src/geom/cuboid.rs, src/geom/ellipse.rs, src/geom/graph/edge.rs, src/geom/graph/mod.rs, src/geom/graph/node.rs, src/geom/line.rs, src/geom/mod.rs, src/geom/polygon.rs, src/geom/polyline.rs, src/geom/quad.rs, src/geom/rect.rs, src/geom/tri.rs, src/geom/vertex.rs, src/lib.rs, src/math.rs
The `geom::Graph` should be useful for composing together multiple
geometric primitives (tris, quads, cuboids, other graphs, etc). See the
`graph` and `Graph` documentation for more details. This should be
useful for building the `Graphics` API, combining a geometry graph with
some sort of colour and texture mapping for nodes/vertices.
Moves the `Vertex` traits into a `vertex` submodule.
Adds `Polygon`, `Ellipse` and `Quad` types that wrap their respective
module's functions with a single type.
Adds some missing iterator implementations to some primitive geom types.
=>  Add a `geom::Graph` for composing together geometric primitives (along with other `Graph`s)

src/geom/range.rs, src/geom/rect.rs, src/lib.rs, src/math.rs, src/prelude.rs, src/rand.rs
Also adds a doc example of how to use `Range::lerp` (see code below).
Closes #74.
Closes #73.
Closes #80.
Closes #82.
Closes #88.
Closes #91.
=> Add `Range::lerp` method. Add missing `Rect` constructors. Add many new items to prelude.

src/osc/mod.rs
`127.0.0.1` is a particularly poor default for osc senders as they're
only able to send to that same port. `0.0.0.0` binds to all network
interfaces (rather than just the loopback interface) and so is a
reasonable default that should "just work" in most cases. It seems that
`osc.js` also does this and it seems that Max/MSP does too (though I'm
not certain).
=> Change OSC default binding address from `127.0.0.1` to `0.0.0.0`

src/app.rs, src/lib.rs, src/window.rs
This enables fullscreen shortcuts by default, however they can easily be
disabled / enabled via the `App::set_fullscreen_on_shortcut` method.
The fullscreen shortcuts are currently as follows:
- Linux: `F11`
- MacOS: `CMD + f`
- Windows: `WIN + f`
Currently this uses a custom `is_fullscreen` method to perform the
toggling, however this should probably be provided by winit upstream.
Currently only tested on Linux + Gnome.
=> Add fullscreen toggle keyboard shortcuts.

examples/simple_draw.rs, src/app.rs, src/lib.rs, src/state.rs
Please see the changes to the `simple_draw.rs` example to see how to
update your code for these changes.
Closes #71.
=> Remove `app.window.*` fields in favour of `app.window_rect()` method

examples/simple_draw.rs, src/app.rs, src/lib.rs
From the docs:
> The time in seconds since the `App` started running.
> 
> Primarily, this field is a convenience that removes the need to call
> `app.duration.since_start.secs()`. Normally we would try to avoid using
> such an ambiguous field name, however due to the sheer amount of use
> that this value has we feel it is beneficial to provide easier access.
> 
> This value is of the same type as the scalar value used for describing
> space in animations.  This makes it very easy to animate graphics and
> create changes over time without having to cast values or repeatedly
> calculate it from a `Duration` type. A small example might be
> `app.time.sin()` for simple oscillation behaviour.
> 
> **Note:** This is suitable for use in short sketches, however should be
> avoided in long …
=> Add simple accessor field for getting the time since app start in secs

Cargo.toml, README.md, nannou-new/src/main.rs
Changes include:
- Update to glium 0.21.0, fixing lots of mac bugs.
- Update to conrod 0.59.0.
- Removed `app.window.*` fields in favour of `app.window_rect()`.
- Vsync and multisampling are now enabled by default. These can be
disabled via the associated window builder methods.
- Add support for toggling fullscreen via standard keyboard shortcuts.
- Add `Draw::line` method.
- Fix `draw::Background` color API.
- Fix OSC default binding address.
- Add `Range::lerp` method.
- Add some missing `Rect` constructors.
- Add a bunch of named colours under `nannou::color::named`. These are
imported via the prelude.
=> Publish 0.5.0.

Cargo.toml, src/ui.rs
This method allows the user to specify when they only want to draw if
the `Ui` has changed visually since the last time `Ui::draw_to_frame` or
`Ui::draw_to_frame_if_changed` was called.
=> Add `Ui::draw_to_frame_if_changed` method which only draws if necessary

src/app.rs, src/lib.rs, src/ui.rs
The app proxy now checks a flag to determine whether or not to call the
`winit::EventsLoopProxy::wakeup` method and in turn the underlying OS
wakeup function. This flag indicates whether or not the event loop is
currently "asleep" aka waiting for input events. The proxy will now only
wakeup the main event loop if the flag indicates that the event loop is
currently asleep.
This should allow the user to call the `wakeup` method as often as they
want without unnecessarily triggering the underlying OS wakeup function
which on some systems can cause lock contention and significant CPU
increase.
=> Improve the efficiency of the App proxy by only calling OS when needed

examples/osc_receiver.rs, examples/osc_sender.rs, examples/simple_ui.rs, src/app.rs, src/lib.rs, src/ui.rs, src/window.rs
- Fix bug in DPI usage within Window::inner_size_points method
- **Ui::draw** methods no longer clear the screen to black.
- **App::new_ui** no longer requires specifying a window, instead a
window can be optionally specified via a builder method. The focused
window is used by default.
- **window::Builder::build** now sets the window as the app's
`focused_window` if none is currently set.
=> Fix DPI bug, Ui API tweaks, Add `App::window_id`, Improve default focused window

src/app.rs, src/lib.rs
Returns the number of times the App's `view` function has been called
(and completed) since the start of the program.
Closes #127.
=> Add `App::elapsed_frames` method

CHANGELOG.md, src/math.rs
Ran into an issue during the workshop where the mapped result was out of
range of the target type's value range, but because `unwrap` was used it
was difficult to find where unwrap was occuring. This should make any
invalid casts much more obvious.
=> Add better `panic!` message to `map_range` if cast fails

CHANGELOG.md, Cargo.toml, examples/simple_polygon.rs, src/draw/drawing.rs, src/draw/mesh/vertex.rs, src/draw/mod.rs, src/draw/properties/mod.rs, src/draw/properties/primitive/mod.rs, src/draw/properties/primitive/polygon.rs, src/geom/polygon.rs, src/mesh/vertex.rs
This involved a large update to the inner **IntoDrawn** API used for mapping `Drawing`s of geometric primitives to their "meshed" representation. The overhaul now allows for a dynamic number of arbitrary vertices per drawn primitive without requiring the need to reallocate buffers on each draw call.
The `Drawing` API has also been updated to allow for builders to produce new `Drawing` types. This allows for typed ordering of builder methods. E.g. `draw.polygon().points(points)` produces a `Drawing<Polygon<Fill>>` which implements `SetColor`, while `draw.polygon().colored_points(points)` produces a `Drawing<Polygon<PerVertex>>` which does not (as the color is specified via the vertices).
`draw.polygon()` supports both "filled" coloring and per-vertex coloring. A `simple_polygon.rs` example …
=> Implement `draw.polygon()` API

CHANGELOG.md, Cargo.toml, examples/simple_mesh.rs, src/draw/backend/glium.rs, src/draw/drawing.rs, src/draw/mesh/vertex.rs, src/draw/mod.rs, src/draw/properties/mod.rs, src/draw/properties/primitive/mesh.rs, src/draw/properties/primitive/mod.rs, src/draw/properties/primitive/polygon.rs
Allows for drawing a mesh via a sequence of triangles. The triangles can
be provided either as a sequence of `Tri<V>` or via a sequence of
vertices alongside a sequence of indices into those vertices.
The `IntoDrawn` trait API has been changed to allow for a more flexible
`Indices` type. The `Indices` type now has access to the Draw's
intermediary mesh each time the next index is requested.
The `GeomVertexData` has been changed to `IntermediaryMesh` and a
`indices` buffer has been added in order to support indexed vertices.
This will be useful for the `draw.mesh()` API.
An `IntoVertex` trait has been added which should aid in simplifying the
`draw.mesh()` API.
=> Add `draw.mesh()` API. Add `simple_mesh.rs` example. Add `IntoVertex` trait.

nannou-new/Cargo.toml, nannou-new/README.md, nannou-new/src/main.rs
This means we no longer need to update the generated `nannou` crate
version each time nannou is updated.
Also adds some crate-level docs and notes to the README.
`nannou-new` should now be ready for publishing.
Closes #137.
=> Update nannou-new to use cargo for retrieving version and template

src/osc/recv.rs, src/osc/send.rs
This was causing an issue where sometimes an osc example would fail while a socket attempted to bind to an address.
=> Make sure osc examples do not run during testing

CHANGELOG.md, examples/nature_of_code/chp_02_forces/2_10_exercise_attract_repel.rs, examples/nature_of_code/chp_02_forces/2_6_attraction.rs, examples/nature_of_code/chp_02_forces/2_7_attraction_many.rs, examples/nature_of_code/chp_03_oscillation/3_02_forces_angular_motion.rs, examples/nature_of_code/chp_03_oscillation/3_10_exercise_oop_wave.rs, src/rand.rs
This avoids a common `panic!` that would occur when the `min` value is
greater than the `max` value. Rather than `panic!`ing, we simply swap
the min and max values instead.
=> Change `random_range` to check that `min <= max`

CHANGELOG.md, src/geom/vector.rs
For example, this implements `From<Point2<S>>` for `Point3<S>`,
`From<(S, S)>` for `Point3<S>` and so on. The element added during
conversion is always zeroed.
=> Add expanding conversion trait implementations for Vector types

nannou-new/Cargo.toml, nannou-new/src/main.rs
Published as 0.1.1.
Closes #211.
=> [nannou-new] Create `assets` directory when generating project

CHANGELOG.md, src/window.rs
These map directly to the underlying winit window methods.
=> Add `Window::grab_cursor` and `Window::hide_cursor` methods

examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, src/draw/backend/vulkano.rs, src/ui.rs, src/window.rs
This significantly simplifies the process of creating and maintaining
swapchain image framebuffers, currently probably the most tedious part
of using raw vulkan with nannou. See the docs for the new
`window::SwapchainFramebuffers` type and its `update` method for more
details on how it works under the hood.
This significantly simplifies the `ui` and `draw` backends, as well as
the raw vulkan examples as a result. The easiest way to see the impact
of this PR is probably to check the diff for the vk examples.
cc @JoshuaBatty should be a good start on this simplification process!
=> Create a `SwapchainFramebuffers` type

src/app.rs, src/window.rs
This should fix the issue where the GPU would lag behind the CPU on
macos.
For **v0.9**.
Related to vulkano-rs/vulkano#1135.
=> Change `RefreshSync` loop mode to wait on previous frame presentation

CHANGELOG.md, src/app.rs, src/event.rs, src/lib.rs, src/prelude.rs, src/state.rs, src/time.rs
The idea behind the `Duration` type was to extend the std `Duration`
with simple methods for retrieving useful time units with a `f64`
representation. This approach was unwieldy and confusing to use in
practise as it required constantly converting between the `std` and
nannou `Duration` types.
Having the new `DurationF64` trait in the prelude should simplify things
by extending the `std::time::Duration` type the methods directly.
Closes #255 
Closes #234.
=> Remove `state::time::Duration` in favour of a `time::DurationF64` trait.

CHANGELOG.md, src/gpu.rs, src/window.rs
See the vulkano `ColorSpace` documentation
[here](https://docs.rs/vulkano/0.11.1/vulkano/swapchain/enum.ColorSpace.html)
for the motivation behind this change.
=> Prefer sRGB color formats when building swapchain

src/app.rs, src/window.rs
Nannou will now fall back to the `Fifo` present mode if `Mailbox` is
not supported by the swapchain when switching the `Wait` or `Rate`
`LoopMode`s.
This should fix the issue on macos where certain examples that use the
`Wait` or `Rate` loop modes would `panic!` with an
`UnsupportedPresentMode` error.
Closes #262.
@freesig could you confirm that this fixes the `simple_ui.rs` example
for you? It's probably also worth checking that the `loop_mode.rs` works
now too as that example switches between all of the different loop modes
one at a time on keypress.
Closes #262
=> Fallback to `Fifo` present mode if `Mailbox` is unavailable

Cargo.toml, examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/app.rs, src/draw/backend/vulkano.rs, src/frame/mod.rs, src/frame/raw.rs, src/gpu.rs, src/lib.rs, src/prelude.rs, src/ui.rs, src/window.rs
This new `Frame` image acts as an intermediary buffer between the user's
graphics and the swapchain image for presentation.
See #224 for more details.
This is a **WIP** as the `draw` and `ui` graphics interop have not been
updated to account for the updated `Frame` type. Many of the `vk_*`
examples also still require updating.
=> Add intermediary image to `Frame` for user graphics

src/window.rs
This allows for specifying a custom logical device queue for a window's
swapchain during the window building process via the
`vulkan_device_queue` method.
Custom device extensions can also now be specified via the
`vulkan_device_extensions` builder method.
See method documentation for more details.
=> Add support for custom queue or device extensions per window

examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, src/draw/backend/vulkano.rs, src/frame/mod.rs, src/gpu.rs, src/prelude.rs, src/ui.rs
Also includes an `Fbo` alias for the new `FramebufferObject` type.
The `ViewFramebuffer` type has been replaced with a
`ViewFramebufferObject` type along with a `ViewFbo` type alias.
This new type uses the `Fbo` internally, greatly simlifying the
implementation.
Closes #214.
cc @JoshuaBatty this should simplify all the post-processing stuff heaps!
=> Add `FramebufferObject` type to simplify working with framebuffers.

examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, src/gpu.rs
Allows for building a `Sampler` type by chaining together a series of
parameters, or falling back to defaults. Defaults values can be
retrieved via the `SamplerBuilder::DEFAULT_*` associated consts.
Closes #255
cc @JoshuaBatty another handy tool for simplifying post-processing
boilerplate
=> Add a `SamplerBuilder` type for modular Sampler build process

examples/vulkan/vk_compute_shader.rs, examples/vulkan/vk_debug.rs, examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/controls.rs, examples/vulkan/vk_quad_warp/vk_quad_warp.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/app.rs, src/draw/backend/vulkano.rs, src/frame/mod.rs, src/frame/raw.rs, src/lib.rs, src/prelude.rs, src/ui.rs, src/vk.rs, src/window.rs
Also removes the `gpu` module in favour of the new `vk` module.
Many vulkano items have been re-exported into the `vk` module as well to
avoid name repetition and ease access to common types. Items that would
have an ambiguous meaning if they were to be re-exported have been left
out of the re-export list.
Methods and fields on the `App` and `Window` types starting with `vulkan_`
have been renamed to start with `vk_`.
See the examples for how to update and rid of your boilerplate today!
=> Embrace the `vk` prefix. Re-export vulkano via a new `vk` module.

examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/vk_quad_warp.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/draw/backend/vulkano.rs, src/vk.rs
This simplifies the viewport creation process by removing the need to
specify the origin and depth_range, which can use reasonable defaults in
the vast majority of cases.
The defaults can be retrieved via `ViewportBuilder::DEFAULT_ORIGIN` and
`ViewportBuilder::DEFAULT_DEPTH_RANGE`.
=> Add a `ViewportBuilder` type.

src/vk.rs
use vulkano::instance::loader::DynamicLibraryLoader was missing from the vk.rs file which meant it would throw an error when compiling on mac.
=> Adding in DynamicLibraryLoader to vk.rs

examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_triangle.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/draw/backend/vulkano.rs, src/prelude.rs, src/vk.rs
This adds a trait that allows for specifying `DynamicState` params via
builder methods, allowing the user to not have to think about `scissors`
or `line_width` until they have to.
=> Add `DynamicStateBuilder` trait to ease `DynamicState` creation

README.md
This adds
1. The nannou logo to the top of the readme
2. 6 gifs showing some examples that come with Nannou
3. Better HQ versions of cargo compile and simple_draw example
=> updating the README with fancier gifs

tests/run_all_examples.rs
This adds an example that runs each nannou example listed in the
Cargo.toml for a few seconds each, one at a time.
This is useful for finding `panic!`s that only occur at runtime, as
while `cargo test` does compile the examples, it does not try and
execute them.
The test has the `#[ignore]` attribute so that `cargo test` does not run
the example by default. This is because 1. the test takes a looong time
to run and 2. travis is likely incapable of running a lot of the tests
as it doesn't have a windowing system etc. As a result, to run the test
locally use `cargo test -- --ignored`. We should try to ensure we run
this at least once before publishing each major release.
Specifically, this test was created to help with testing for vulkano
image layout bugs (#271). cc @freesig just pinging …
=> Add test that runs every nannou example listed in the Cargo.toml

examples/nature_of_code/chp_07_cellular_automata/7_04_exercise_wolfram_ca_scrolling.rs
Currently writing a test that runs all examples one at a time locally
and noticed that this example was `panic!`ing with a subtraction
underflow error. I've changed it to use signed integers instead to avoid
`panic!`.
However, it still seems to behave a bit strangely. I can't see any of the
1-dimensional CA patterns until the rows reach the top of the window and
after that they start disappearing.
@JoshuaBatty I'll probs merge this PR as is, but after could you maybe
try running this to see if it's behaving as intended sometime? I wonder
if the odd behaviour is a side-effect of the change where the background
no longer automatically clears? I remember you mentioning you were doing
something to work around that a while back, maybe whatever that is isn't
needed anymore?
=> Fix panic in nature of code CA example 7_04

Cargo.toml, src/lib.rs, src/ui.rs
In order to update winit and rebase nannou_patches to the latest master
of vulkano, conrod's vulkano dependency also had to be updated.
I'll hold off publishing a new version of conrod_vulkano until we can
land whatever the necessary image layout fix is in vulkano and get a new
vulkano version published. Until then, v0.9 will use a branch of the
conrod crates called `update_vulkano_nannou_patches`.
=> [v0.9] Rebase vulkano nannou_patches branch onto master. Update winit.

examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/vk_quad_warp.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/draw/backend/vulkano.rs, src/frame/mod.rs, src/ui.rs
The `nannou_patches` vulkano branch was recently updated to use @freesig's patch (rebased onto master under one of my branches) that seems to remove the need for specifying initial/final layout hacks within renderpasses. This PR accounts for this by removing all explicit mentions of layouts within renderpass declarations.
Tested successfully with the `run_all_examples` test locally.
=> Remove explicitly specified initial and final layouts from all renderpass instances

Cargo.toml, examples/laser/laser_frame_stream.rs, examples/laser/laser_frame_stream_gui.rs, examples/laser/laser_raw_stream.rs
Recently I started a new crate for discovering and streaming to laser
DACs called [**lasy**][1]. This commit adds two examples demonstrating
how to work with both the RawStream and FrameStream APIs from the new
crate.
The **laser_raw_stream.rs** example demonstrates how to feed points to a
raw stream by drawing a single point at a position controlled by the
position of the mouse within the window.
The **laser_frame_stream.rs** example demonstrates how to feed points
to a frame stream by switching between different test patterns with the 1, 2,
3 and 4 keys.
Both examples could be improved in the future by targeting all lasers
detected (rather than just the first) and using the
`ether-dream-dac-emulator` crate to assist with creating a visualisation
of what the DAC is outputting. Currently …
=> Add an `examples/laser` directory demonstrating laser streams from the new `lasy` crate.

Cargo.toml, examples/laser/laser_frame_stream.rs, examples/laser/laser_raw_stream.rs
Switch to stable dependencies for vulkano and conrod!
Now that vulkano 0.12.0 is out we're able to start stabilising
dependencies!
All that's left is to stabilise the `shade_runner` dev-dependency (used
within the `vk_hotload.rs` example) and we'll be able to publish v0.9!
This PR also fixes a couple of warnings appearing in the laser stream examples.
=> Switch to stable dependencies for vulkano and conrod!

README.md
This saves on info duplication and keeps the README a bit cleaner!
=> Remove most README contents in favour of pointing to the guide

src/app.rs, src/state.rs
Helpful for tracking if you're hitting a good fps. When nannou supports text, we can also have a convenience method for rendering the fps to the frame.
=> Add fps convenience method to app

.travis.yml, examples/vulkan/vk_compute_shader.rs, examples/vulkan/vk_hotload.rs, examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/vk_quad_warp.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/app.rs, src/draw/backend/vulkano.rs, src/frame/mod.rs, src/state.rs, src/ui.rs, src/vk.rs, src/window.rs
This does not address the audio or osc modules as they will be moved
into independent crates as of #331 and #334.
=> Address new trait dynamic dispatch syntax warning from latest nightly

.travis.yml, Cargo.toml, examples/simple_audio.rs, examples/simple_audio_file.rs
For the most part not a lot has changed, however nannou_audio 0.2 now
supports alternative audio host APIs including ASIO on windows via the
`asio` feature.
=> Update simple_audio example for nannou_audio v0.2.0 release

src/app.rs, src/ui.rs, src/vk.rs
The current implementation is a bit of a hack but at least enables users
who are blocked by this while we work out a proper solution in the
meantime!
Closes #303.
Related to #365 (should hopefully close it).
cc @freesig does look alright for now?
=> Remove depth format constants in favour of querying supported formats

CHANGELOG.md, Cargo.toml, examples/vulkan/vk_image.rs
Time for v0.10! Here are some of the main changes to look out for:
**Colour Overhaul** #355
The **palette** crate dependency has been updated from v0.2 to v0.4.
Nannou's old named colours (e.g. DARK_BLUE, PURPLE, etc based on the
Tango desktop color selection) have been removed in favour of using the
named colours provided by palette which are much more extensive and
based on the the CSS spec. This means there's a high chance some of your
code or colors might break! In some cases certain colours will be
missing, in other cases the colour may now look different. We've added a
new `named_color_reference.rs` example that should hopefully make it a
little easier to find equivalent colours from the new selection.
Friendlier colour constructors have been added to the prelude, so e.g.
now we can …
=> Publish nannou 0.10.0. Update the CHANGELOG. 

examples/nature_of_code/chp_02_forces/2_5_fluid_resistance.rs
There is some duplication in code I found.
The new code is not identical to the previous version since `m` was picked randomly from `1.0..4.0`, but `new_random` picks it from `0.5..4.0`
=> Refactor Nature of Code's 2_5 example

CHANGELOG.md, examples/multi_window_draw.rs, examples/nature_of_code/chp_01_vectors/1_7_motion101.rs, examples/nature_of_code/chp_01_vectors/1_8_motion101_acceleration.rs, examples/nature_of_code/chp_01_vectors/1_9_motion101_acceleration.rs, examples/nature_of_code/chp_08_fractals/8_2_recursion.rs, src/app.rs
This solves a `panic!` that would occur when the app's draw renderer
would be re-used between multiple windows.
Closes #376.
=> Use a unique `draw::backend::vulkano::Renderer` per window

Cargo.toml, src/io.rs, src/ui.rs
This addresses the #380.
The `notosans` crate is behind a `notosans` feature which is enabled by
default. To disable this dependency (which may help to remove roughly
~800kb of total binary size), use the `--no-default-features` flag. In
the case that the `notosans` feature is disabled, the `Ui` will attempt
to load the first font discovered in `assets/fonts`. If no fonts exist,
an error will be returned.
Closes #380.
=> Use the `notosans` crate to guarantee default font availability.

CHANGELOG.md, Cargo.toml
This fixes an issue where some Linux distros (Arch, Void, possibly
others) are unable to build 0.5.1. 0.6.1 includes the fix, hence the
update.
Merge pending freesig/shade_runner#21 and updating the dep in the cargo.toml.
=> Update vulkano and shaderc deps to fix Linux build issues

Cargo.toml, examples/simple_text.rs, examples/simple_text_path.rs, src/app.rs, src/draw/backend/vulkano.rs, src/draw/drawing.rs, src/draw/mod.rs, src/draw/primitive/mod.rs, src/draw/primitive/polygon.rs, src/draw/primitive/text.rs, src/draw/properties/mod.rs, src/draw/theme.rs, src/lib.rs, src/prelude.rs, src/text/cursor.rs, src/text/font.rs, src/text/glyph.rs, src/text/layout.rs, src/text/line.rs, src/text/mod.rs, src/ui.rs
The new text module extends the `rusttype` crate with simplified interop
with nannou's geometry types and provides functionality for handling
layout of aligned and justified multi-line text.
The new `draw.text("some text")` API takes advantage of this new
module to allow for displaying multi-line text, handling line
wrapping, alignment, justification, font sizes and different fonts.
TODO:
path tessellation.
to avoid the need for specifying complicated lifetimes in the `Text`
type itself in a fairly efficient manner.
likely copy the implementation of the Ui's glyph cache.
single text instance.
- ~~Add a font map to the `Draw` API state.~~ *Bailing on this in favour of using fonts directly.*
of the glyph cache. For now, assume tex_coords channel in main draw
mesh refers to text cache image …
=>  Add a `text` module providing various items useful for text layout. Begin work on `draw.text("some text")` API (WIP).

CHANGELOG.md, Cargo.toml
The main features of this version are:
- Integrate lyon! Fixes many 2D bugs and adds a `Path` API. #375
- Add a `text` module and `draw.text("foo")` API. #388
- Adds a `notosans` feature to guarantee a default, fallback font. #384
- Many new examples have been added and old ones improved. #394 #391
- Fixes a bug where shaderc would not build on some linux distros. #386
- Fixes a bug where `app.draw()` couldn't be used in multiple windows. #378 
Feel free to check out the CHANGELOG for some more details!
=> Publish 0.11.0. Update CHANGELOG with recent text and font changes.

src/text/font.rs, src/text/mod.rs, src/ui.rs
Currently, the `Ui` constructor method unnecessarily returns an Error if
the assets directory cannot be found, even if the `notosans` feature is
enabled. This commit changes the behaviour to attempt to use the
`notosans` crate font if the feature is enabled and only attempt to
discover the assets directory if the feature is disabled.
=> Fix an issue with fallback font detection in Ui construction

Cargo.toml, src/text/mod.rs
This patch release includes 3 major fixes:
- Fixes a bug that occurred when drawing a mesh after a path #404.
- Fixes an issue where text could not be positioned #403.
- Fixes a bug where UI default font detection failed when assets directory did not exist #405.
=> Publish 0.11.1 - Includes three major fixes for 0.11.

Cargo.toml, examples/vulkan/vk_compute_shader_rendering.rs, src/frame/raw.rs
I am interested in rendering the output of some compute shaders to the swap chain.
I added the `dispatch()` method to `AddCommands` related to `AutoCommandBufferBuilder`, so that compute pipeline execution and graphics rendering can take place in the same command buffer.
I also added an example to show one use case.
I saw the comment `Note that certain builder methods are *not* provided in order to avoid unexpected behaviour`  in `raw.rs`... was this one intentionally left out?
=> Add the method `dispatch` to AddComands for AutoCommandBufferBuilder

examples/vulkan/vk_compute_shader_rendering.rs, examples/vulkan/vk_hotload.rs, examples/vulkan/vk_image.rs, examples/vulkan/vk_image_sequence.rs, examples/vulkan/vk_images.rs, examples/vulkan/vk_quad_warp/vk_quad_warp.rs, examples/vulkan/vk_quad_warp/warp.rs, examples/vulkan/vk_shader_include/mod.rs, examples/vulkan/vk_teapot.rs, examples/vulkan/vk_teapot_camera.rs, examples/vulkan/vk_triangle.rs, examples/vulkan/vk_triangle_raw_frame.rs, src/draw/backend/vulkano.rs, src/frame/mod.rs, src/frame/raw.rs, src/ui.rs
Remove the argument `secondary` from the methods `begin_render_pass()` and `next_subpass()` of the command buffer builder `AddCommands`.
This change is motivated by the fact that `AddCommands` doesn't offer the possibility to use secondary command buffers, which means that `secondary` had to be always set to `false`.
=> Remove `secondary` from methods of the command buffer builder

.travis.yml
(Disclaimer: I'm a very newbie to Rust. I'm sorry if my understanding is wrong...)
Since it seems `cargo doc` is a separate thing from `cargo test`, I think it can be moved to a separate job to reduce the time per job so that it'll be less likely to be timed out.
Besides, I added `--no-deps` option. If I understand correctly, it's not necessary to generate documents for all the dependencies just to test the nannou's doc is correct, right?
=> Use a separate job for validating docs

.travis.yml, CHANGELOG.md, Cargo.toml, src/app.rs, src/vk.rs
_Currently pending freesig/shade_runner#22 being merged and published._
This one is mostly to address an issue some macOS users have been
running into with an old version of the `metal` crate. Updating conrod
for this also has the nice benefit that the `TextEdit` and `TextBox`
widgets now support copy/paste, double-click-select and
shift-click-select!
Some small sections of the Vulkan API have required some breaking
changes while updating to a later version of the spec, though they are
minor and can be found in the code diff for this commit.
See the CHANGELOG for full note.
Closes #418.
=> Update vulkano, conrod and shade_runner. Publish 0.12.

nannou-new/Cargo.toml, nannou-new/src/main.rs
I was looking into #448 so I tried to build the `nannou-new` binary but it is failing because of the 2018 edition changes, it can't find the `cargo` crate.
- set the edition to 2018 in the _Cargo.toml_ file.
This is the required change to fix the build
- update dependencies and make the required changes
- fix issue with downloading a random version of the `nannou` package
I didn't investigate if this happens with the previous cargo version, but in the 0.42 the `query` method doesn't yield a package summary in any order, so the last one that is downloaded could be any version.
=> [nannou-new] Fix build with 2018 edition

examples/capture_hi_res.rs, examples/simple_capture.rs, src/app.rs
This fixes a bug where the `app.project_dir()` method would return the
path to the nannou build dependency directory rather than the actual
project directory. This PR fixes this issue.
Renames `project_dir` to `project_path` in order to match the
`assets_path` convention.
=> Fix `app.project_dir()`, rename to `app.project_path()`

src/ui.rs, src/wgpu/texture/mod.rs
This makes interop with other wgpu crates a lot easier.
=>  Expose the inner `TextureHandle` from the `Texture`.  Add a `Texture::into_ui_image` method .

CHANGELOG.md, examples/wgpu/wgpu_compute_shader/wgpu_compute_shader.rs, examples/wgpu/wgpu_image/wgpu_image.rs, examples/wgpu/wgpu_image_sequence/wgpu_image_sequence.rs, examples/wgpu/wgpu_teapot/wgpu_teapot.rs, examples/wgpu/wgpu_teapot_camera/wgpu_teapot_camera.rs, examples/wgpu/wgpu_triangle/wgpu_triangle.rs, examples/wgpu/wgpu_triangle_raw_frame/wgpu_triangle_raw_frame.rs, src/draw/backend/wgpu/mod.rs, src/wgpu/bind_group_builder.rs, src/wgpu/mod.rs, src/wgpu/render_pass.rs, src/wgpu/render_pipeline_builder.rs, src/wgpu/texture/mod.rs, src/wgpu/texture/reshaper/mod.rs
The process of creating the bind group, render pipeline and their layouts can be quite tedious and explicit. This is great for reducing the chance of errors, but is perhaps not so ergonomic for the creative coding workflow where we'd like to throw together new pipelines quickly and easily.
The aim for these new types is to provide this quick-and-easy API by falling back to reasonable defaults in the case that some parameter has not been specified. All defaults have been exposed as constants on the associated builder types.
=> Add a suite of builder types to simplify bind group and pipeline creation

src/window.rs
Hi there,
I made the meaning of "size" (for windows) more explicit by refering to width and height and thus explaining the return values. (Size itself might also imply the area.) No code changes.
Cheers,
tpltnt
=> Window doc fix: explicit tuple

Cargo.toml, src/app.rs, src/event.rs
This PR fixes "redraw event in non-redraw phase" on window resize/move by updating to winit 0.22. See [winit #1382](https://github.com/rust-windowing/winit/issues/1382).
=> Fix "redraw event in non-redraw phase"

examples/wgpu/wgpu_compute_shader/shaders/shader.comp, examples/wgpu/wgpu_image/shaders/shader.frag, examples/wgpu/wgpu_image/shaders/shader.vert, examples/wgpu/wgpu_image_sequence/shaders/shader.frag, examples/wgpu/wgpu_image_sequence/shaders/shader.vert, examples/wgpu/wgpu_teapot/shaders/shader.frag, examples/wgpu/wgpu_teapot/shaders/shader.vert, examples/wgpu/wgpu_teapot_camera/shaders/shader.frag, examples/wgpu/wgpu_teapot_camera/shaders/shader.vert, examples/wgpu/wgpu_triangle/shaders/shader.frag, examples/wgpu/wgpu_triangle/shaders/shader.vert, examples/wgpu/wgpu_triangle_raw_frame/shaders/shader.frag, examples/wgpu/wgpu_triangle_raw_frame/shaders/shader.vert
Fix names of the generated SPIR-V files in the comments (which were all invariably `vert.spv`) and remove the `-o ...` argument since it corresponds to the default pattern for the name of the generated file.
=> Fix comments for the generation of SPIR-V files in wgpu examples

nannou/src/wgpu/render_pipeline_builder.rs
Probably left over from a previous refactoring step.
=> Remove unnecessary code

examples/wgpu/wgpu_compute_shader/wgpu_compute_shader.rs, examples/wgpu/wgpu_image/wgpu_image.rs, examples/wgpu/wgpu_image_sequence/wgpu_image_sequence.rs, examples/wgpu/wgpu_teapot/wgpu_teapot.rs, examples/wgpu/wgpu_teapot_camera/wgpu_teapot_camera.rs, examples/wgpu/wgpu_triangle/wgpu_triangle.rs, examples/wgpu/wgpu_triangle_raw_frame/wgpu_triangle_raw_frame.rs, nannou/src/draw/renderer/mod.rs, nannou/src/wgpu/mod.rs, nannou/src/wgpu/texture/reshaper/mod.rs, nannou_isf/src/pipeline.rs
wgpu::shader_from_spirv_bytes() reduces the amount of code required for loading shaders.
=> Add function wgpu::shader_from_spirv_bytes()

nannou_timeline/Cargo.toml
This makes it a little easier to ensure that `nannou_timeline` on master
also builds with `nannou` on master. Also acts as a nice version bump
check when publishing new crate versions.
=> Depend on `nannou` by both version and path in `nannou_timeline`

CHANGELOG.md, examples/Cargo.toml, examples/laser/laser_ffi.rs, nannou_laser/Cargo.toml, nannou_laser/cbindgen.toml, nannou_laser/src/dac.rs, nannou_laser/src/ffi.rs, nannou_laser/src/lib.rs
This greatly simplifies the process of detecting laser DACs
asynchronously, particularly for languages other than Rust where thread
safety is like the wild west.
=> Add nonblocking LASER DAC detection. Polish `nannou_laser::ffi`.

README.md
the current link only works for people that have already been invited to the channel. This updates the link so users can then request and invite to be sent to them in order to join the slack channel.
=> fixes broken nannou slack invite link in readme

Cargo.toml, scripts/run_all_examples/main.rs, scripts/set_version/Cargo.toml, scripts/set_version/main.rs
This updates the package version for each of the `nannou` and `nannou_*`
crates and also updates the dependencies and dev-dependencies of all
crates in the workspace to refer to the new version.
This should be useful for synchronising the versions of all crates when
publishing.
=> Add a new script for setting the version of all nannou crates

.github/workflows/nannou.yml
This adds a workflow that will automatically try to publish the `nannou`
and `nannou_*` crates every time a commit is pushed to `master`.
The idea is that we can now run `cargo run -p set_version -- X.Y.Z`,
commit the version update and push to the repo and the github action
will automatically publish all versions that have been incremented.
Another nice benefit is that contributors can now open their own PRs to
update crate versions. Maintainers are only required to merge, and no
longer need to manually run `cargo publish` locally.
This workflow may need a little tweaking over the next couple of
releases as its difficult to test until it comes time to make a release.
=> Automate publishing nannou repositories if version is changed

nannou/src/app.rs, nannou/src/prelude.rs, nannou/src/window.rs
Currently, the fullscreen API is a little unwieldy, especially for such a
common task! This PR aims to simplify things by applying the changes
described in #487 and #496.
Closes #487.
Closes #496.
cc @capogreco @felixfaire
=> Simplify the fullscreen API

nannou_laser/Cargo.toml, nannou_laser/src/stream/frame/opt.rs, nannou_laser/src/stream/raw.rs
This PR removes `nannou_laser`'s dependency on the `failure` and
`derive_more` crates in favour of the more minimal, library-friendly
`thiserror` crate.
Also removes the `hashbrown` dependency in favour of using the `std`
hash collections as I believe the `hashbrown` optimisations have since
been applied to `std`.
This removes the need for about ~15 upstream crates.
Closes #520.
=> Remove some unnecessary dependencies from `nannou_laser`

nannou_laser/src/ffi.rs, nannou_laser/src/stream/frame/mod.rs
Also adds some more detailed documentation to the `ffi` module.
=> Expose missing `set_<param>` methods on LASER stream types via FFI

guide/src/tutorials/basics/drawing-2d-shapes.md
It seems the example in `drawing-2d-shapes.md` is broken in the latest version. This fixes it.
I am curious, though, if there is an equivalent to the behaviour of `colored_points` to give each line segment a different colour?
=> changed `color_points` to `points`

examples/laser/laser_ffi.rs, examples/laser/laser_frame_stream_gui.rs, nannou_laser/src/ffi.rs, nannou_laser/src/lib.rs, nannou_laser/src/stream/frame/mod.rs, nannou_laser/src/stream/mod.rs, nannou_laser/src/stream/raw.rs
This adds the ability to add a stream error callback function to both
the raw and frame stream types during building.
An action can be specified to take in response to the error. Options
include attempting to re-detect the DAC, reconnect to the TCP stream and
closing the stream thread.
Methods have also been added to the stream types to allow for checking
whether or not the stream has been closed, and for closing the stream
manually and checking the result.
The `ffi` module has been updated to provide access to this new
functionality.
=> Support for stream error handling to nannou_laser

guide/README.md, guide/src/why_nannou.md
This removes the Travis CI badge for the previous standalone guide repo. I didn't see a guide-specific workflow in the actions (https://github.com/nannou-org/nannou/actions). Lemme know if the guide readme should use the overall badge, or maybe there should be a guide-specific workflow?
=> Small guide fixes

examples/Cargo.toml, examples/draw/draw_arrow.rs, nannou/src/draw/mod.rs, nannou/src/draw/primitive/arrow.rs, nannou/src/draw/primitive/line.rs, nannou/src/draw/primitive/mod.rs, nannou/src/draw/primitive/polygon.rs, nannou/src/draw/renderer/mod.rs, nannou/src/draw/theme.rs
The new API is almost identical to `draw.line()`, except that you can
also specify the `.head_length(l)` and `.head_width(w)` if you wish. By
default, these are equal to `weight * 4.0` and `weight * 2.0`
respectively.
This might be particularly useful for things like vector field
visualisations or for debugging.
=> Add a `draw.arrow()` API. Include a new `draw_arrow.rs` example

nannou/src/app.rs, nannou/src/color/mod.rs, nannou/src/draw/mod.rs, nannou/src/ease.rs, nannou/src/event.rs, nannou/src/geom/range.rs, nannou/src/math.rs, nannou/src/rand.rs, nannou/src/state.rs, nannou/src/ui.rs, nannou/src/wgpu/texture/mod.rs, nannou/src/window.rs, scripts/set_version/Cargo.toml
Added some clarifications to things I was wondering about (e.g. `map_range` not clamping output, `Resized` values in points, etc.).
Also fixes some broken internal links I found. (Maybe one day rust-lang/rust#43466 will land! In the meantime, I wonder if we could do a manual check that links in the generated output are valid? Might look into this, if you think it's worthwhile.)
=> Some documentation fixes

guide/src/tutorials.md, guide/src/tutorials/draw/animating-a-circle.md
It seems some of the links on this page won't work: https://guide.nannou.cc/tutorials.html
(Btw, the tutorials looks nicer than when I tried long ago! Thank you so much for your efforts.)
=> Fix broken links on the index page of tutorials

nannou/src/geom/vector.rs
I don't think the current implementation of `(other - self).angle()` is correct. The angle between (1, 0) and (0, 1) should be PI, but this function gives 0.
I think `other.angle() - self.angle()` is what was meant.
Also fwiw, I took a look at the implementations in [Processing](https://github.com/processing/processing/blob/8e86389c7e017d0e4d61f81fb942c25e3ed348c7/core/src/processing/core/PVector.java#L987) and [p5.js](https://github.com/processing/p5.js/blob/1.0.0/src/math/p5.Vector.js#L1293). They both use the dot product / product of magnitudes formula, which i guess uses less trig operations and might be a faster? Maybe benchmarking this can be a separate issue though.
(Another note is that they both do clamping due to floating point issues, which I don't _think_ the …
=> fix implementation of angle_between

examples/Cargo.toml, examples/laser/laser_ilda_idtf.rs, nannou_laser/Cargo.toml, nannou_laser/src/ilda_idtf.rs, nannou_laser/src/lib.rs
Adds support for ILDA Image Data Transfer Format to `nannou_laser`
behind a `ilda-idtf` feature. This feature adds a `ilda_idtf` module and
which re-exports the `ilda-idtf` crate and extends it with a
`FrameReader`. `FrameReader` simplifies the process of reading ILDA IDTF
files into frames that are compatible with `nannou_laser`.
An example demonstrating the new API has been added under
`examples/laser/laser_ilda_idtf.rs`.
=> Add `ilda-idtf` feature to `nannou_laser`

examples/Cargo.toml, examples/ui/simple_ui.rs, examples/ui/timeline_demo.rs, nannou/src/ui.rs
This long overdue re-export simplifies the process of generating widget
IDs for nannou GUIs. The ui examples have been updated to demonstrate
how to take advantage of the macro.
=> Re-export `widget_ids!` macro from `nannou::ui`

nature_of_code/chp_01_vectors/1_5_vector_magnitude.rs
Rect should be aligned to top left of win. The old example drew half of the rect outside of win rect bounds.
=> Example 1-5 Vector Magnitude: fix rect alignment

nannou/src/geom/rect.rs
Just a minor change to the doc comments for the rect l_r_b_t function, so that it reflects the actual order of the tuple. I think this should resolve any ambiguities or confusion regarding the order of edges that get returned.
=> change doc comments for lrgt fn to reflect tuple order

nannou_laser/Cargo.toml
Upon trying to build, I encountered
```
Compiling nannou_laser v0.14.1 (/home/leaf/prog/nannou/nannou_laser)
error[E0425]: cannot find function `connect_timeout` in module `ether_dream::dac::stream`
--> nannou_laser/src/stream/raw.rs:669:52
|
669 |         Some(timeout) => ether_dream::dac::stream::connect_timeout(&broadcast, ip, timeout)
|                                                    ^^^^^^^^^^^^^^^ not found in `ether_dream::dac::stream`
error[E0599]: no method named `set_timeout` found for struct `ether_dream::RecvDacBroadcasts` in the current scope
--> nannou_laser/src/dac.rs:80:29
|
80 |         self.dac_broadcasts.set_timeout(duration)
|                             ^^^^^^^^^^^ method not found in `ether_dream::RecvDacBroadcasts`
error[E0599]: no method named `set_nonblocking` …
```
=> Update ether-dream version for nannou_laser

guide/src/changelog.md, nannou_laser/Cargo.toml
See changelog diff for details.
=> Update lasy dependency of nannou_laser. Publish nannou_laser 0.14.2.

guide/src/changelog.md, nannou_laser/Cargo.toml, nannou_laser/src/ffi.rs, nannou_laser/src/lib.rs, nannou_laser/src/stream/frame.rs, nannou_laser/src/stream/mod.rs
This allows for enabling/disabling draw path reordering for frames
submitted to the LASER frame stream. See the docs for the new
`enable_draw_reorder` methods for more details.
=> [nannou_laser] Add support for toggling draw path reordering

examples/draw/draw_mesh.rs
The comment stated "Clear the background to blue" where the function clearly painted the background black.
=> Fix wrong comment on examples/draw/draw_mesh.rs

generative_design/random_and_noise/m_1_3_02.rs, generative_design/random_and_noise/m_1_3_03.rs
As reported in issue #609 the two generative examples m_1_3_02 and m_1_3_03 only produce a black window. 
I've done some digging today and have noticed that there seems to be an issue with sampling from a `Rgba16Float` texture in WPGU. Updating these examples textures so they now instead use `.format(wgpu::TextureFormat::Rgba8Unorm)` fixes this issue and the examples draw as expected. 
closes #609
=> fixes m_1_3_02 and m_1_3_03 generative examples

generative_design/data_trees/m_5_1_01.rs, generative_design/dynamic_data_structure/m_6_1_02.rs, generative_design/dynamic_data_structure/m_6_1_03.rs, generative_design/image/p_4_3_2_01.rs, generative_design/oscillation_figures/m_2_3_01.rs, generative_design/random_and_noise/m_1_2_01.rs, generative_design/shape/p_2_0_02.rs, generative_design/shape/p_2_0_03.rs, generative_design/shape/p_2_2_1_01.rs, generative_design/shape/p_2_2_3_01.rs, generative_design/shape/p_2_2_5_01.rs, generative_design/shape/p_2_3_1_01.rs
Just a handful of typos I noticed when going through the examples.
Several examples mention using the backspace button, but the functionality does not appear to work (only the delete button)... it was unclear if the code should be fixed or the comments updated. Just for posterity... they were:
- p_4_1_2_01.rs
- p_4_1_2_02.rs
- m_1_5_03.rs
- m_1_5_04.rs
- p_2_2_3_01.rs
- p_2_2_6_01.rs
- p_2_3_1_01.rs
- p_2_3_3_01.rs
=> Correct typos in Generative Design example comments

guide/book_tests/Cargo.toml
A recent change to cargo has started causing tests generated by
`rust-skeptic` to fail. budziq/rust-skeptic#120. This has started
causing [issues with our CI](https://github.com/nannou-org/nannou/pull/636/checks?check_run_id=920796725).
This PR temporarily switches to a branch with a patch for this issue. We
should remove this once budziq/rust-skeptic#121 is merged and published.
=> Temporary switch to `rust-skeptic` patch to fix CI for book tests

generative_design/shape/p_2_1_1_03.rs, generative_design/shape/p_2_1_3_05.rs, generative_design/shape/p_2_2_1_02.rs
p_2_1_1_03 was updated to better mirror the behavior for keys 3 and 4 found in https://editor.p5js.org/generative-design/sketches/P_2_1_1_03 - basically the transparency is calculated per line rather than one transparency for all lines. If you'd rather this be in a separate PR then let me know.
The rest of the changes for the three files were related to avoiding the overflow errors when not running with `--release`
=> Fix generative design overflows

nature_of_code/chp_03_oscillation/3_01_angular_motion.rs
Fixed the NOC example from page 126, in the on branch example version the balls do not follow the line rotation.
Added the expected behavior and also improved the color and renamed `a_velocity` to `angle_velocity` and `a_acceleration` to `angle_acceleration`
=> Fixed not working example from NOC

nannou/src/draw/drawing.rs
Correct documentation for {x,y,z}_degrees functions to say "in degrees" instead of "in radians", which is incorrect.
=> Correct small mistake in coordinate_degrees functions documentation

examples/Cargo.toml, examples/audio/record_wav.rs
The example shows how to create an input stream, record audio and write it to disk in .wav format. Because of nannou's interactive nature, I couldn't help but add a record indicator and basic controls to play and pause the stream. Related to issue #435
=> Port CPAL's record_wav example to nannou

examples/wgpu/wgpu_instancing/wgpu_instancing.rs
As noted in #596, this fixes the y axis for the wgpu_instancing example. Let me know if I missed something and I'll pick it up!
=> Fix orientation of the teapot y axis in wgpu_instancing example

examples/Cargo.toml, generative_design/Cargo.toml, guide/book_tests/Cargo.toml, guide/src/changelog.md, guide/src/contributing.md, guide/src/getting_started/create_a_project.md, nannou/Cargo.toml, nannou_audio/Cargo.toml, nannou_isf/Cargo.toml, nannou_laser/Cargo.toml, nannou_new/Cargo.toml, nannou_osc/Cargo.toml, nannou_package/Cargo.toml, nannou_timeline/Cargo.toml, nature_of_code/Cargo.toml
See the changelog below for an overview of the changes included in this
version.
For the most part, this is an update for wgpu 0.5. @alekspickle
already has a WIP for wgpu 0.6 at #655! I'm more than happy to publish a
new version again as soon as that lands, but figured this one is already
well overdue :)
Also, find out how you can get new nannou versions published quicker in
the new Contributing chapter of the guide [here](https://guide.nannou.cc/contributing/publishing-new-versions.html)).
=> Publish version 0.15

nannou_timeline/src/env/mod.rs, nannou_timeline/src/timeline.rs, nannou_timeline/src/track/automation/bang.rs, nannou_timeline/src/track/automation/dynamic.rs, nannou_timeline/src/track/automation/numeric.rs, nannou_timeline/src/track/ruler.rs
The title says it all.
It was automated using [comby](https://comby.dev/) and this [pattern](https://catalog.comby.dev/#redundant-field-names-single).
As a suggestion, maybe this could be automated with GitHub Actions
=> Refactor: use shorthand fields

examples/audio/feedback.rs, examples/audio/record_wav.rs, guide/src/changelog.md, nannou_audio/Cargo.toml, nannou_audio/src/device.rs, nannou_audio/src/lib.rs, nannou_audio/src/receiver.rs, nannou_audio/src/requester.rs, nannou_audio/src/stream/input.rs, nannou_audio/src/stream/mod.rs, nannou_audio/src/stream/output.rs
Finishes off the work started by @JoshuaBatty at #662.
We still need to provide a nice way of accessing the timestamps now
provided to CPAL streams. I'll open up a following issues with more
details on what makes this tricky in `nannou_audio`.
TODO
=> Update `nannou_audio` to latest `cpal` and `dasp_sample` versions 

guide/src/getting_started/platform-specific_setup.md, guide/src/tutorials.md
Nothing huge, just came across this when setting up to use nannou on Debian Buster. The vulkan-utils package is transitional now. I'm unsure if this affects any other distros.
=> update Getting Started "vulkan-utils" reference for Debian Buster and other guide changes

examples/Cargo.toml, nannou/src/math.rs, nannou/src/wgpu/texture/image.rs, nannou_isf/src/pipeline.rs
They confused me a bit when building for the first time (much slower) because I didn't realise they were warnings until the app window popped up, so I figured it would be worth saving someone else that confusion. :smiley: 
The bulk of them are converting deprecated `to_rgba` calls to `to_rgba8`, also adding a missing debug value to `unwrap_or_panic`.
=> Fix warnings emitted when running draw example

nannou/src/draw/mod.rs
Hello, I'm just starting out with nannou and it seems amazing so far!
I noticed that the non-uniform scaling functions `scale_x`, `scale_y` and `scale_z` scale all other dimensions to zero. I suppose this is unintentional. Or am I misunderstanding something?
=> Fix non-uniform scaling

guide/src/tutorials/osc/osc-introduction.md
Hi, I've been following the guide and doing the tutorials. 
When I checked the latest version of nannou_osc, it was different from the one in the guide.
=> Fix osc version in the guide

nannou/Cargo.toml, nannou/src/app.rs, nannou/src/wgpu/texture/capturer.rs
Use `instant::Instant` instead of `std::time::Instant`.
`instant::Instant` is a type alias for `std::time::Instant` on non-WASM environments. On WASM environments, however, `Instant` is replaced by a browser-friendly implementation which doesn't crash when `Instant::now` is called (which would be the case with `std::time::Instant`).
Relates to #475
=> Use instant crate for WASM compatibility

guide/src/changelog.md, nannou/src/app.rs, nannou/src/wgpu/texture/image.rs
Also ensures we don't print to stderr on Outdated swapchain texture -
instead we just ignore the error.
=> Update changelog for wgpu 0.6 changes

nannou/src/wgpu/mod.rs
Changes `Powerpreference` to use `default`
=> Powerpreference default

examples/draw/draw_capture_hi_res.rs, examples/wgpu/wgpu_compute_shader/wgpu_compute_shader.rs, examples/wgpu/wgpu_image/wgpu_image.rs, examples/wgpu/wgpu_image_sequence/wgpu_image_sequence.rs, examples/wgpu/wgpu_instancing/wgpu_instancing.rs, examples/wgpu/wgpu_teapot/wgpu_teapot.rs, examples/wgpu/wgpu_teapot_camera/wgpu_teapot_camera.rs, nannou/Cargo.toml, nannou/src/draw/mod.rs, nannou/src/draw/renderer/mod.rs, nannou/src/frame/mod.rs, nannou/src/ui.rs, nannou/src/wgpu/bind_group_builder.rs, nannou/src/wgpu/blend.rs, nannou/src/wgpu/device_map.rs, nannou/src/wgpu/mod.rs, nannou/src/wgpu/render_pass.rs, nannou/src/wgpu/render_pipeline_builder.rs, nannou/src/wgpu/sampler_builder.rs, nannou/src/wgpu/texture/capturer.rs, nannou/src/wgpu/texture/image.rs, nannou/src/wgpu/texture/mod.rs, nannou/src/wgpu/texture/reshaper/mod.rs, nannou/src/window.rs, nannou_isf/src/pipeline.rs, nannou_timeline/Cargo.toml
This consists of pretty simple name changes for the most part, however there is some pretty significant restructuring of the `RenderPipelineDescriptor`. This meant quite a few changes in the `render_pipeline_builder` module - I tried improving the builder method docs here while I was at it.
The `Sampler` binding type now requires that you specify whether or not it uses `Linear` filtering for any of its minify, magnify or mipmap filters. A `wgpu::sampler_filtering` function was added to make it a little easier to retrieve this bool from the `SamplerDescriptor` type. That said, this does require a little extra boilerplate for graphics pipelines that involve a texture sampler. I think the `wgpu_image.rs` example is probably the simplest example of how to update for this.
---
@danwilhelm …
=> Update wgpu to 0.7, conrod to 0.72, winit to 0.24.

examples/draw/draw_text.rs, nannou/src/draw/primitive/text.rs
Adds a new method that colors text glyphs individually. 
For example, this could be useful for:
- Quickly colorizing the first character or word of a string. 
- Displaying syntax-highlighted code.
For an example, see `draw_text.rs`. Tested by running the examples, `cargo test`, and `cargo fmt`.
=> Add ability to color characters individually, update draw_text example

CHANGELOG.md, examples/Cargo.toml, generative_design/Cargo.toml, guide/book_tests/Cargo.toml, guide/src/changelog.md, guide/src/getting_started/create_a_project.md, nannou/Cargo.toml, nannou_audio/Cargo.toml, nannou_isf/Cargo.toml, nannou_laser/Cargo.toml, nannou_new/Cargo.toml, nannou_osc/Cargo.toml, nannou_package/Cargo.toml, nannou_timeline/Cargo.toml, nature_of_code/Cargo.toml
It's time!
Notable changes include the update from wgpu 0.5 to 0.7, a bunch of
bug fixes for graphics related stuff, and an update of dependencies and
related APIs in `nannou_audio`. See the `guide/src/changelog.md`
diff for a detailed list of the changes included in this release.
I think I mentioned on matrix that I was hoping to get #684 into this
release, but then realised that `nannou_isf` is still unpublished
anyway, so we can publish it at 0.16 if/when those changes are ready.
=> Publish 0.16 - Update changelog with related changes

guide/src/getting_started/platform-specific_setup.md
Per issue #691, the initial example command in the getting started guide fails to build if `cmake` has not been installed. I've just added simple directions to install cmake using [Homebrew](https://brew.sh)
=> Issue #691 Adding cmake to OS X setup directions

nannou_laser/Cargo.toml
Currently the `ilda` and `ffi` features are missing.
=> nannou_laser - enable all features for docs.rs

nannou/Cargo.toml
Enabling palette's `serializing` feature allows colors to be saved to config files easily.
=> Enable serializing of color types

nannou/src/draw/mod.rs
Hi, I've just noticed the documentation for `Draw#triangle_mode` is not correct. This commit will fix it.
=> fix(docs): correct the triangle_mode docs

nature_of_code/chp_03_oscillation/3_04_exercise_spiral.rs
When running the 3_04 exercise on Windows, the background is completely
black, so the spiral path is not visible. I tested on my mac, the
background, without being set, is green, so it kinda works on macOS.
Nevertheless, this commit sets the background to white on the first
frame so it can work on both Windows and macOS and be consistent with
the Nature of Code's example, which has the white background as well.
=> fix: NOC 3_04 exercise to work on Windows

nannou/src/draw/primitive/text.rs, nannou/src/text/line.rs
When wrapping text, `Info` (and the enclosed `Break`) records the byte and character indexes of each wrapped line.
**Problem.** Currently, the byte index refers to the original string, but the char index does not. For example:
```
let s1 = "fn main() {\n    nannou::app(model)\n";              // Byte index is into original string
let s2 = "fn\n main(\n) {\n    \nnanno\nu::app\n(mode\nl)\n";  // Char index is into "wrapped" string
```
**Proposed Solution.** I propose making the byte and character indexes both refer to the original string, to avoid confusion. Currently, the char index is always incremented by 1 every break, even if the break itself is 0 chars (`""`), 1 char (`" "`, `"\n"`), or 2 chars (`"\r\n"`). It does not skip these end-of-break chars, even though the byte index skips …
=> Ensure `Info` char index refers to orig string

nannou/Cargo.toml, nannou_timeline/Cargo.toml
See the wgpu changelog [here](https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md).
For the most part, this just seems to be some fixes and extra validation checks! It looks like we've managed to dodge all breakage both here and upstream in `conrod_wgpu`.
=> Update conrod to 0.74 and wgpu to 0.9

examples/Cargo.toml, generative_design/Cargo.toml, guide/book_tests/Cargo.toml, guide/src/changelog.md, guide/src/getting_started/create_a_project.md, nannou/Cargo.toml, nannou_audio/Cargo.toml, nannou_core/Cargo.toml, nannou_core/README.md, nannou_isf/Cargo.toml, nannou_laser/Cargo.toml, nannou_new/Cargo.toml, nannou_osc/Cargo.toml, nannou_package/Cargo.toml, nannou_timeline/Cargo.toml, nature_of_code/Cargo.toml
Be sure to see the updated `guide/src/changelog.md` for details on the included changes.
Updates `noise` from 0.6 to 0.7, removing a much older duplicated version of the image dependency from nannou's dependency graph.
Also adds a README to the `nannou_core` crate, the contents of which are copied from the crate's root-level documentation (mostly to satisfy the cargo.toml metadata requirements).
=> Publish version 0.17 - Includes `wgpu` 0.9 update, `nannou_core`, text fixes and more.

nannou/src/app.rs
Motivation: I found a typo while reading the docs.
Summary: Fixed the typo.
=> Fix typo in `src/app.rs`

nannou_core/Cargo.toml
See changelog [here](https://github.com/bitshifter/glam-rs/blob/1da7d6459c5f9890275c7fc1871e6c33c825b6b9/CHANGELOG.md).
I need this for the Add and Sub implementations on scalar types, eg Vec2 + f32
=> Update glam to 0.17

examples/audio/feedback.rs, examples/audio/hrtf-noise.rs, examples/audio/record_wav.rs, examples/audio/simple_audio.rs, examples/audio/simple_audio_file.rs, nannou/src/window.rs
Fixes #652 
Fixes #483 
**Rationale**
Currently, Windows audio examples crash, because on Windows [`winit` drag and drop requires multi-threaded COM](https://github.com/rust-windowing/winit/issues/1185). This interferes with other crates such as `cpal` and `nannou_audio` on the same thread. This PR allows Windows users to use `nannou_audio` easily on the same thread by disabling `winit` drag and drop. Unfortunately, this solution will not work for Windows users who want both audio and drag and drop.
**Alternatives**
The most common alternative is [spawning `cpal` on another thread](https://github.com/RustAudio/rodio/issues/214#issuecomment-643640535). Other libraries have taken this approach [such as `ruffle`](https://github.com/ruffle-rs/ruffle/blob/master/desktop/src/audio.rs#L77). …
=> Add disable drag-and-drop method for cpal+winit Windows compatibility

README.md, guide/src/SUMMARY.md, guide/src/changelog.md, guide/src/community_tutorials.md, guide/src/welcome.md, nannou/src/window.rs
- Add community tutorials section to guide.
- Disable conditional compilation warning (to resolve unused variable warning on non-Windows from #773).
- Update changelog.
=> Add community tutorials, disable warnings in conditional compilation

examples/audio/feedback.rs, examples/audio/hrtf-noise.rs, examples/audio/record_wav.rs, examples/audio/simple_audio.rs, examples/audio/simple_audio_file.rs, guide/src/changelog.md, nannou/src/window.rs
Removes Windows-specific option to disable drag-and-drop.
This function was originally included to allow `cpal` and `winit` to co-exist on the same thread. However, [`cpal` now uses a compatible threading model](https://github.com/RustAudio/cpal/pull/597).
=> Remove Windows drag-and-drop method

nannou/Cargo.toml, nannou/src/lib.rs
Since daggy isn't used anywhere in the crate, this just bumps the version number in `nannou/Cargo.toml`.
=> Remove daggy (unused dependency)

generative_design/data_trees/m_5_1_01.rs, generative_design/shape/p_2_2_3_01.rs, generative_design/type/p_3_2_1_01.rs, nannou/Cargo.toml, nannou/src/draw/mesh/builder.rs, nannou/src/draw/primitive/ellipse.rs, nannou/src/draw/primitive/path.rs, nannou/src/geom/path.rs
The bug in #799 has been fixed in lyon 0.17.10. This PR updates to the latest version of lyon, updating the affected code. However, this restricts the functionality of the `nannou::geom::path::Builder` since much of its interface has been moved to SVG-only builders. In particular functions like `move_to` and `arc` can only be used through a `lyon::path::builder::WithSvg<nannou::geom::path::Builder>` with the lyon-specific types, making them less user-friendly.
It would be possible to store a `WithSvg<Builder` directly in `nannou::geom::path::Builder` and implement the `SvgPathBuilder` trait instead of `PathBuilder` to restore much of the lost functionality. Although, I don't know if the added convenience is worth the added complexity, since the `Builder` API seems to be pretty low-level …
=> Update lyon to version 0.17

examples/nannou_basics/loop_mode.rs, guide/src/changelog.md, nannou/src/app.rs, nannou_timeline/src/track/mod.rs
Created two methods, for `SketchBuilder` and `Builder` respectively, which allow for specifying an initial LoopMode. Updated the relevant example to showcase the new functionality and fixed an unrelated, lingering code warning.
This resolves #528.
=> Specifying an initial, default LoopMode.

nannou/src/app.rs
Pending some clarity from the `winit` maintainers about whether wait interruptions without events are allowed, this is an idea for a fix for `LoopMode::Wait` if they are.
See https://github.com/rust-windowing/winit/issues/1985 for more info.
Fixes #781
=> Don't update model in LoopMode::Wait when there were no events

examples/Cargo.toml, generative_design/Cargo.toml, guide/book_tests/Cargo.toml, guide/src/changelog.md, nannou/Cargo.toml, nannou_audio/Cargo.toml, nannou_conrod/Cargo.toml, nannou_core/Cargo.toml, nannou_isf/Cargo.toml, nannou_laser/Cargo.toml, nannou_mesh/Cargo.toml, nannou_new/Cargo.toml, nannou_osc/Cargo.toml, nannou_package/Cargo.toml, nannou_timeline/Cargo.toml, nannou_wgpu/Cargo.toml, nature_of_code/Cargo.toml
This contains the update from `wgpu` version `0.9` to `0.11`, the new
`lyon` version `0.17`, the release of some newly refactored `nannou_*`
crates and many other fixes and tweaks.
See the updated changelog for details!
In particular:
> 
> **Note:** As of wgpu 0.10, all nannou projects now require either:
> 
> 1. The following line in their top-level cargo manifest:
>    ```toml
>    resolver = "2"
>    ```
>    OR
> 2. All packages must use the 2021 edition (or later) of Rust, e.g.
>    ```toml
>    edition = "2021"
>    ```
> 
> This requirement is due to wgpu 0.10's reliance on the new version of cargo's
> dependency resolver and how it unifies features. Without either of the above
> amendments, you will likely run into strange upstream compilation errors. You
> can read more about the …
=> Publish version 0.18. Includes wgpu 0.11, lyon 0.17 and more

README.md
The community inviter system we use for people to join the nannou slack has been broken for a while now. This new link will now allow people to hopefully auto-join.
=> updated the slack invite link in the README

nannou/src/app.rs, nannou_wgpu/src/lib.rs
To enable WASM support in Nannou we should aim for WPGU's WebGL2 backend first since WebGPU support in browsers is still very experimental.
This PR proposes to add `Backends::GL` to the list of default backends s.t. running a Nannou app in the browser does not fail with `BuildError::NoAvailableAdapter`.
=> Add GL backend to default backends for better WASM support

nannou/Cargo.toml, nannou_conrod/Cargo.toml, nannou_wgpu/Cargo.toml
This PR explicitly lifts wgpu to 0.11.1 which fixes some driver compatibility regressions and is compatible with winit 0.26.0.
winit 0.26.0 has the `web-sys` feature flag removed which I take as a commitment to builtin / reliable WASM support.
Not entirely sure about it but I think this PR also lifts the `rustflags = ["--cfg", "web_sys_unstable_apis"]` requirement of #715. As a result I propose to merge this PR before #715.
=> Update wgpu and winit to the latest version

.cargo/config.toml, .github/workflows/nannou.yml, nannou/Cargo.toml
This is all @Woyten's awesome work in #715 on nannou's WASM compatibility story, but with the `winit/web-sys` feature removed seeing as `winit` have themselves also removed the feature.
Closes #715.
=> Woyten's "Make Nannou compile in WASM environment" without old `winit/web-sys` feature

nannou/src/app.rs, nannou/src/window.rs
This PR exposes a set of `async` functions that are sufficient to run a Nannou app on WASM. The change is conservative i.e. it only exposes a minimal set of functions and it preserves the behavior of the old non-`async` functions.
=> Add async twin functions for WASM support

nannou/src/geom/path.rs
As part of the lyon 0.17 upgrade, the `move_to` method got removed from
the builder. This makes it impossible to start a path/subpath without
having to access the underlying lyon Builder.
This commit exposes the `begin()` method in nannou's Builder, which is
what `move_to` got renamed to in lyon.
closes: #806
=> Expose `begin()` method in `geom::path::Builder`

nannou/src/app.rs
After landing #782 I noticed that the `App` proxy's `wakeup` method
hasn't been functional since the last event loop refactor (when wgpu was
introduced).
I also noticed that #782 makes the extra updates provided in the `Wait`
loop mode redundant. Previously, we ensured at least ~3 updates would
occur following the most recently received event. This was aimed at
allowing GUI's to update for a couple of extra frames to resolve subtle
1-3 frame animations, but I'm unsure this is really the right approach.
At the very least, the number of updates should be configurable as a
part of the `LoopMode::Wait` variant, but that can wait for a future PR.
=> Ensure `wakeup` calls (`UserEvent`s) provide updates in `Wait` mode

nannou/src/window.rs
When running window managers such `i3`, it is nice to be able to specify rules for certain classes of windows. Currently, `nannou` doesn't set this attribute when making a X11 window, thus the `class` attribute in X11 is set to the window title by default.
This PR adds `nannou` as the window class, so that you can for example in `i3` put this in your config file to open all nannou windows as floating windows:
```
for_window [class="nannou"] floating enabled
```
Since `X` is running on multiple OSes, I have not added any config check for this. This will only have effect on systems actually running `X`.
=> Set window class for X11 running apps

.cargo/config.toml, nannou/Cargo.toml
This PR is another split-off of #811. It enables `wgpu/webgl` when the `nannou/wasm-experimental` is active. It also removes the strange `.cargo/config.toml` file which seems not to be required when using `winit 0.26.0`.
=> Enable wgpu/webgl when WASM feature is enabled

guide/src/changelog.md
I've picked a handful of non-breaking commits for a nannou 0.18.1
release. I've omitted the wasm related commits until 0.19 due to the
winit version update which is technically breaking, even though unlikely
to cause issues.
=> Add changelog entry for nannou 0.18.1 and unreleased wasm changes

examples/Cargo.toml, examples/wgpu/wgpu_compute_shader/wgpu_compute_shader.rs, nannou/Cargo.toml, nannou/src/app.rs, nannou/src/window.rs, nannou_wgpu/Cargo.toml, nannou_wgpu/src/device_map.rs, nannou_wgpu/src/texture/capturer.rs
This PR fixes #826 without reverting the `async` functions.
Since I didn't manage to make the code run using the `futures` library I tried using `async-std` instead which I perceive as a very solid `async` replacement for `std`.
One problem remains: Nannou is not terminating properly. It might have something to do with daemon threads now being non-daemon threads.
=> Fix #826 / Use async-std instead of futures

nannou/Cargo.toml, nannou/src/window.rs
I managed to execute my synthesizer [microwave](https://github.com/Woyten/tune/tree/master/microwave) in Firefox using WGPU's WebGL2 backend. A running demo can be tested [here](https://woyten.github.io/microwave/). The graphics is super fast but the audio (without any parameter tuning) is surprisingly slow and underruns on my Firefox. As a side note, audio has always been a problem during my WASM experiments and seems to be a weak point of CPAL.
The path to WASM via WebGL seems straightforward:
- Adapt the code s.t. it can be compiled to WASM (#702 and #715)
- Expose some `async` Nannou functions since blocking is unsupported in browsers (#815)
- Use `wgpu`'s `webgl` feature (#822)
- Add `Backends::GL` to the list of default backends (#812)
- Reduce the device limits to …
=> Make Nannou run in WASM environment

generative_design/color/p_1_2_2_01.rs
"Generative Design" example "p_1_2_2_01" lacks `Grayscale` arm.
The params of the added code is based on original "Generative Gestaltung" book.
=> Add  `Grayscale` arm in `generative_design/color/p_1_2_2_01.rs`

nannou/Cargo.toml
I just noticed that while `0.18.1` is published, it isn't updated on master! I must have opened the `publish-nannou-0.18.1` branch but forgot to merge it into master too. Doing so now!
=> Merge missing "publish nannou version 0.18.1" commit into master

.github/workflows/nannou.yml
This should help to re-use build artifacts from previous CI passes for each job when possible.
=> Speedup CI jobs using rust-cache action

examples/Cargo.toml, examples/ui/egui/simple_ui.rs
This PR will add a new example: `examples/ui/egui/simple_ui.rs`, it's the egui version of an old example found here: https://github.com/nannou-org/nannou_conrod/blob/main/examples/simple_ui.rs. As requested in #856.
I'm relatively new to nannou and this is my first contribution so don't be afraid to tell me how I can do better!
Closes #856
=> Port old conrod example "simple_ui" to egui

README.md
The second GIF in the README was leading to a non-existing page
=> Fix broken example link in readme

examples/draw/draw_arrow.rs
Solves issue #810 because it does not panic at value 0 or close to 0.
=> Removed panic when mouse is on origin of arrow. Solves #810

nannou_osc/Cargo.toml, nannou_osc/src/lib.rs
Also re-export new types.
Had this lying around for a few months, thought we could land this too before publishing new versions post #940.
=> `nannou_osc`: update `rosc` from `0.1` to `0.10`

nannou_egui/Cargo.toml
The new recommendation is to follow the SPDX 2.1 standard. This allows automatic license verification software to work properly. Reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
=> Update license field following SPDX 2.1 license expression standard

nature_of_code/chp_01_vectors/1_10_motion101_acceleration.rs, nature_of_code/chp_01_vectors/1_11_motion101_acceleration_array.rs
When the distance vector between the mouse coordinates and Mover is zero, the calculation results in `NaN` as it tries to `normalize()` it. (Blank screen is displayed.)
I found `normalize_or_zero()` in the docs and this would be great alternative for the case.
=> Fix nature_of_code/chp_01_vectors example

.github/workflows/nannou.yml, Cargo.lock, Cargo.toml, bevy_nannou/Cargo.toml, bevy_nannou/README.md, bevy_nannou/src/lib.rs, bevy_nannou_draw/Cargo.toml, bevy_nannou_draw/src/lib.rs, bevy_nannou_render/Cargo.toml, bevy_nannou_render/src/lib.rs, bevy_nannou_wgpu/Cargo.toml, bevy_nannou_wgpu/src/lib.rs, nannou_isf/src/pipeline.rs
Provides initial crates/plugins for #951.
Right now, we're targeting the main branch of `bevy`. Due to the speed of the ecosystem, it's better (imo) to find out about breaking changes sooner than later as we are in our dev mode. If this becomes annoying with CI, we can always target a specific sha.
=> Scaffold initial bevy plugin #951 

.github/workflows/nannou.yml, Cargo.lock, Cargo.toml, default.nix, examples/Cargo.toml, flake.lock, flake.nix, guide/src/contributing.md, guide/src/contributing/nix-shell.md, nannou_isf/Cargo.toml, nannou_isf/tests/gen_glsl.rs, shell.nix
These can be ignored by most users, but will be useful for Nix folks and may help to simplify our CI a little.
The default.nix can also be used as a CI-checked reference of what system dependencies and env vars are required on Linux and macOS.
Tested successfully on `x86_64-linux` and `aarch64-darwin`.
---
The `hotglsl` crate was updated to 0.2 in order to switch from the `glsl-to-spirv` crate to the pure-Rust `naga` removing the need for some system deps like libclang.
=> Add a Nix flake along with a package derivation (default.nix) and dev shell (shell.nix). Update hotglsl.

bevy_nannou/src/main.rs, bevy_nannou_draw/src/lib.rs, bevy_nannou_render/src/draw_function.rs, bevy_nannou_render/src/lib.rs, bevy_nannou_render/src/pipeline.rs, bevy_nannou_render/src/shaders/nannou.wgsl, bevy_nannou_wgpu/src/bind_group_builder.rs, result
This pull request moves us from using a roughly 1:1 conversion of the rendering technique on `master`, which uses a custom `ViewNode` that runs on Bevy's 3d render graph, to using a variety of "mid-level" render APIs that bring us closer in line with Bevy's idioms for render code.
Rather than executing a series of render commands, we queue a number of render items into the `Transparent3d` phase of Bevy's existing render graph. These items are then executed with a "draw function", which specifies a series of render operations to perform on each item, setting the pipeline, bind groups, and finally issuing a draw call.
This initially poses a problem, because our existing rendering code executes a variety of draw calls against a single mesh, and so isn't easily broken into "items." Unlike …
=> 962 use mid level render apis for render

default.nix, shell.nix
The SDK packages and libiconv have since been included in the nix stdenv for darwin builds. Removing them gets the nannou package building again on macOS 🍎 
cc @supiket
=> fix: Get nannou package derivation and devShell building on macOS

Cargo.lock, bevy_nannou/Cargo.toml, bevy_nannou/src/lib.rs, bevy_nannou_draw/src/draw/mod.rs, bevy_nannou_draw/src/lib.rs, bevy_nannou_draw/src/render.rs, examples/Cargo.toml, examples/assets/shaders/simple_shader.wgsl, examples/bevy/simple.rs, examples/bevy/simple_shader.rs, examples/bevy/windows.rs, nannou/Cargo.toml, nannou/src/app.rs, nannou/src/prelude.rs
A few small changes to make it more ergonomic to use `BevyNannouPlugin` with a plain bevy app:
1. Remove `DrawHolder`. This was probably just an attempt to avoid adding the `Component` trait to `Draw` itself, but isn't necessary.
2. Make `Draw` work with the `PrimaryWindow` that bevy spawns by default.
3. Move clearing `NannouTransient` out of `App` and into `NannouRenderPlugin`. This ensures we despawn any meshes or other transient entities we spawned last frame.
4. Use bevy `0.15` "required components" feature to spawn required camera components when `NannouCamera` is spawned.
5. Misc. cleanup of unused `NannouTexture` code.
See the examples for a few simple uses!
=> Updates to allow easy usage of bevy_nannou with bevy.

default.nix
I *think* this is required for copy-paste behaviour in egui, though I don't quite remember.
=> fix: Add required libxkbcommon input for nannou nix pkg

bevy_nannou_draw/src/render.rs
WebGL appears to have a requirement that initialised buffers must have a non-zero length (or something along these lines). This changes our draw logic to lazily initialise the mesh to work around this requirement.
Closes #998.
cc @tychedelia does this solution look OK?
=> fix: Lazily initialize Mesh in draw commands for webgl2 compat
