Cargo.toml
README.md

Also fills out some of the missing fields in the Cargo.toml.

Add all the fancy badges to README

---

Cargo.toml
src/app.rs
src/lib.rs

Add method for getting absolute path of `assets` directory

---

README.md

Pretty straightforward documentation update, just adds a missing link & removes an unnecessary comma.

Update link to examples.

---

README.md

Describes how to clone the repo and run the examples using cargo.

Add a section to the README describing how to run the examples

---

Cargo.toml
src/event.rs
src/window.rs

Version 0.2 includes almost all changes on master since this repo started! See merged PRs for more details.

Update to conrod 0.57, cpal 0.6, glium 0.19, image 0.18. Publish 0.2.

---

CHANGELOG.md
Cargo.toml
README.md
examples/simple_audio.rs
src/app.rs
src/audio/buffer.rs
src/audio/device.rs
src/audio/mod.rs
src/audio/receiver.rs
src/audio/requester.rs
src/audio/stream/input.rs
src/audio/stream/mod.rs

Would be nice to add an example demonstrating the new input stream suppot soon! Perhaps even a feedback example that passes audio directly from an input stream to an output stream.

Update for CPAL input stream support. Update conrod and glium. Add CHANGELOG.

---

src/draw/background.rs
src/draw/mod.rs
src/draw/properties/mod.rs
src/draw/properties/primitive/quad.rs
src/draw/properties/primitive/rect.rs
src/draw/properties/primitive/tri.rs
src/draw/properties/spatial/position.rs
src/geom/cuboid.rs
src/geom/ellipse.rs
src/geom/graph/edge.rs
src/geom/graph/mod.rs
src/geom/line.rs
src/geom/polyline.rs
src/geom/quad.rs
src/geom/range.rs
src/geom/rect.rs
src/geom/tri.rs
src/mesh/vertex.rs

Correct existing geometry defaults and add missing ones

---

src/window.rs

Fallback to default window name "nannou - <exe_name>" if none given

---

src/draw/background.rs

Update draw::Background coloring API to match `SetColor` API.

---

Cargo.toml

Includes:
- Improving the `draw_to_frame_if_changed` method by return a `bool`
indicating whether or not a new frame was drawn.
- Improve the efficiency of the `app::Proxy::wakeup` method.

Publish 0.5.2

---

README.md

Adds some missing items, sub-items and also adds some useful links.

Update README with more detailed Goals section

---

README.md

Adds some missing steps to the Getting Started guide and adds some
missing resources.

Add some improvements to README (lessons learned from workshop)

---

examples/simple_ui.rs

changed from using conrod widget to draw a background colour to using
nannou to draw an ellipse. There are sliders for controlling scale,
rotation and the resolution of the shape. A button triggers a random
colour for the shape and a XYpad allows the use to position the shape on
the canvas.

Updated the simple_ui example

---

Cargo.toml
examples/basics/7_modules/7_modules.rs
examples/basics/7_modules/ball.rs

Simple example demostrating how to create a seperate module file and
call its methods from a nannou application.

Added in a modules example into the basics folder

---

examples/basics/4_conditionals.rs

Since match statements are super handy and useful in Rust, ive added in
a match statement that picks a background colour based on the mouse Y
Position.

Added in a match statement to the 4_conditionals example

---

CHANGELOG.md
Cargo.toml

Also fixes some date bugs in the CHANGELOG.md.

Update nannou to version 0.7.

---

README.md

Makes sure the gif matches the example that is built. See #161

Use "simple_draw" in README

---

Cargo.toml
examples/nature_of_code/chp_06_agents/6_01_seek.rs
src/geom/vector.rs
tests/geom_tests.rs

- First example in NOC 06
- Tests for Vector2::angle()
- Example docs for Vector2::angle()
Not sure about my coding style but let me know if I should make any changes

Noc 6 01 seek

---

src/window.rs

Fix documentation for Window::set_fullscreen

---

src/audio/stream/mod.rs

Also simplifies an expression with the `Iterator::max_by_key` method.
Closes #205 reported by @freesig.

Avoid infinite loop when finding best sample format for audio stream

---

Cargo.toml
examples/vulkan/vk_debug.rs

The example gives the simplest possible usage but the docs at the top explain how to gain more control over the debugging and validation layers.

Add simple vulkan debug example

---

src/app.rs
src/draw/backend/vulkano.rs

Previously this check was missing, so if a user changed the loop mode
after they created a window, the swapchain would not always match
accordingly until the loop mode changed again. Now, we check for a
change to the loop mode after the user model function is called and
recreate window swapchains if necessary.

Recreate window swapchains if user model requires loop mode change

---

Cargo.toml
src/app.rs
src/gpu.rs
src/lib.rs

This adds mac moltenvk automatic installation to Nannou.
Would love some feedback / a second pair of eyes.
https://github.com/mitchmindtree/vulkano/pull/4 needs to merge before this will work
To test comment out these in your `.bash_profile`
```
#export VULKAN_SDK="$HOME/.vulkan_sdk/macOS"
#export PATH="$VULKAN_SDK/bin:$PATH"
#export DYLD_LIBRARY_PATH="$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH"
#export VK_ICD_FILENAMES="$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json"
#export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"
```
You also might want to
`cd ~`
`mv .vulkan_sdk/ vulkan_sdk_BAK/ `
or if confident 
`rm -fr .vulkan_sdk/`
Before the test.
Then just run any nannou application.

Mac install

---

src/vk.rs

This must have been accidentally dropped when rebasing the
`sampler_builder` branch onto the `mac_install` work! This should fix
any macos build errors that might have been introduced.

Add missing `add_loader` method for macos build

---

src/vk.rs

minor fix to missing extension call

fix missing extensions call

---

README.md

Fix badge formatting in README

---

examples/laser/laser_frame_stream_gui.rs

Connect to all detected DACs in `laser_frame_stream_gui` example

---

src/geom/vector.rs

Hey there!
Super interesting project, thank you for all your work on it!
I've found a ticket that I could easily get started with (namely #304), it's a clarification of the vector.len() doc string.
Cheers!

Update docstring of vector.len(), fixes #304

---

.travis.yml
examples/nature_of_code/chp_06_agents/6_01_seek.rs
examples/simple_polyline.rs
examples/simple_ui.rs
nannou-new/src/main.rs
nannou-package/src/main.rs
src/audio/stream/input.rs
src/audio/stream/output.rs
src/draw/backend/glium.rs
src/draw/drawing.rs
src/event.rs
src/geom/line/join/miter.rs
src/geom/vector.rs
src/lib.rs
src/osc/mod.rs
src/window.rs
tests/run_all_examples.rs

Hi there,
this PR should close #298.
Cheers,
tpltnt

travis rustfmt

---

Cargo.toml
examples/generative_design/color/p_1_1_1_01.rs
examples/generative_design/color/p_1_1_2_01.rs
examples/generative_design/color/p_1_2_1_01.rs
examples/generative_design/color/p_1_2_3_01.rs
examples/generative_design/color/p_1_2_3_03.rs
examples/generative_design/oscillation_figures/m_2_1_01.rs
examples/generative_design/shape/p_2_0_01.rs
examples/generative_design/shape/p_2_0_02.rs
examples/generative_design/shape/p_2_0_03.rs

Adds in more Colour examples from http://www.generative-gestaltung.de/2/
The last 3 colour examples are held up until we can create gradients from a polygon again.

adding in more generative examples

---

Cargo.toml
examples/generative_design/oscillation_figures/m_2_1_01.rs
examples/generative_design/oscillation_figures/m_2_2_01.rs
examples/generative_design/oscillation_figures/m_2_3_01.rs
examples/generative_design/oscillation_figures/m_2_3_02.rs
examples/generative_design/oscillation_figures/m_2_5_01.rs
examples/generative_design/oscillation_figures/m_2_5_02.rs
examples/generative_design/shape/p_2_1_1_01.rs
examples/generative_design/shape/p_2_1_1_02.rs
examples/generative_design/shape/p_2_1_1_03.rs
examples/generative_design/shape/p_2_1_2_01.rs
examples/generative_design/shape/p_2_1_2_02.rs
examples/generative_design/shape/p_2_1_2_03.rs
examples/generative_design/shape/p_2_1_2_04.rs

This PR adds in all of the Oscillation figures examples from Generative Design book 2. It also adds another 7 examples from the Shape chapter.

more generative examples, Oscillation figures & Shape examples

---

src/app.rs

Fix typo in a comment in `app.rs`

---

src/draw/primitive/text.rs

Fix an issue where text position and orientation went unused

---

src/draw/primitive/mesh.rs

This was introduced due to a change that was made to the way
intermediary mesh indices are handled when the draw.path() API was
introduced. The behaviour should now be fixed and users should now be
able to draw any number of shapes, paths or meshes in any order without
issues.
Thanks for reporting @MacTuitui!
Closes #402.

Fix bug where `draw.mesh()` intermediary mesh indices were incorrect

---

examples/generative_design/random_and_noise/m_1_2_01.rs
src/color/mod.rs
src/draw/drawing.rs
src/draw/properties/color.rs
src/prelude.rs

closes  #180
There's gonna be a merge conflict with the other PR I've pushed (PR #431)
I'll fix it depending on which one you merge first.

Adding rgb8 to represent values with bytes

---

Cargo.toml

See [the announcement post](https://nannou.cc/posts/nannou_v0.13) on the
website for more info, or the CHANGELOG for the gritty details.

Publish v0.13.0 - Featuring wgpu, frame capturing and more

---

examples/generative_design/oscillation_figures/m_2_2_01.rs

The drawing was upside down. Now draws correctly.

fixes draw position on m_2_2_01 example

---

examples/generative_design/color/p_1_0_01.rs
examples/generative_design/color/p_1_1_2_01.rs
examples/generative_design/color/p_1_2_1_01.rs
examples/generative_design/color/p_1_2_3_01.rs
examples/generative_design/color/p_1_2_3_02.rs
examples/generative_design/color/p_1_2_3_03.rs
examples/generative_design/oscillation_figures/m_2_1_01.rs
examples/generative_design/oscillation_figures/m_2_2_01.rs
examples/generative_design/oscillation_figures/m_2_3_01.rs
examples/generative_design/oscillation_figures/m_2_3_02.rs
examples/generative_design/oscillation_figures/m_2_5_01.rs
examples/generative_design/oscillation_figures/m_2_5_02.rs
examples/generative_design/random_and_noise/m_1_1_01.rs
examples/generative_design/random_and_noise/m_1_2_01.rs
examples/generative_design/random_and_noise/m_1_3_01.rs
examples/generative_design/shape/p_2_0_01.rs
examples/generative_design/shape/p_2_0_02.rs
examples/generative_design/shape/p_2_0_03.rs
examples/generative_design/shape/p_2_1_1_01.rs
examples/generative_design/shape/p_2_1_1_02.rs
examples/generative_design/shape/p_2_1_1_03.rs
examples/generative_design/shape/p_2_1_2_01.rs
examples/generative_design/shape/p_2_1_2_02.rs
examples/generative_design/shape/p_2_1_2_03.rs
examples/generative_design/shape/p_2_1_2_04.rs
examples/multi_window_draw.rs
src/app.rs

Time to start saving images of fun generative experiments :)

updated the generative examples to save screenshots

---

examples/basics/4_conditionals.rs

Fix a minor issue I commented at https://github.com/nannou-org/nannou/issues/471#issuecomment-599542287.
Append `.run()` after `nannou::sketch()`.

Fix example 4_conditionals

---

examples/README.md

Hi there,
i added a quick hint on how to run the examples and also linked the guide for details. When people look at the examples folder they want to try things. This way people get up and running fast & they can learn about the details later.
Cheers,
tpltnt

readme hint: running examples

---

.github/workflows/nannou.yml

For now, this just triggers the workflow CI by adding the directory with a basic rustfmt check. Will complete this in #497.

Add github workflows to the repository

---

nannou/src/prelude.rs
nannou/src/rand.rs
nature_of_code/chp_09_genetic_algorithms/9_1_ga_shakespeare.rs

now allows to easily generate a random ascii character. The possible characters that can be returned are: 
"ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
0123456789)(*&^%$#@!~. "
The nature of code 9_1_ga_shakespeare example has also been updated to use this function now. @mitchmindtree should I be declaring this asciiset as a const inside the function or is it better if this lives at the top of the rand module?

Add random_ascii() function to rand module

---

nannou/src/draw/primitive/ellipse.rs
nannou/src/draw/primitive/polygon.rs

Previously by default `draw.ellipse()` would use a fixed number of
"sides", regardless of size. This resulted in poor performance in
sketches that used lots of small ellipses.
This PR improves the behaviour by using a single lyon arc resulting in
an adaptive angle tolerance.
A fixed resolution can still be manually specified via
`draw.ellipse().resolution(n)` - in these cases the ellipse will be
drawn with the old method.

Improve `draw.ellipse()` behaviour, better performance at small sizes

---

nannou/src/draw/drawing.rs

Fix incorrect behavior of .z_radians()

---

nannou_osc/src/recv.rs

Sorry, I did this before my morning coffee so no seperate branch but hope it's ok for a small documentation change

add note about message being popped

---

examples/laser/laser_ffi.rs
nannou_laser/src/dac.rs

Also fixes the behaviour of the `laser_ffi.rs` example to connect to the
first DAC it discovers.

Fix an issue where async DAC detector failed to detect multiple DACs

---

nannou/src/color/mod.rs

add rgb_u32 to create color from hex literal

---

examples/draw/draw_texture.rs

Remove window ID related comments in draw_texture.rs

---

nannou/src/geom/vector.rs

These are commonly requested methods, so I thought it was about time
we added them! See the diff for details and doc examples.
Closes #420. :smoking:

Add `vec2.rotate(radians)`, `Vector2::from_angle`, `a.angle_between(b)`, `vec.magnitude()` and `vec.magnitude2()` inherent methods

---

examples/Cargo.toml
examples/nannou_basics/window_coordinates.rs
nannou/src/geom/rect.rs

The aim for this example is to provide an interactive demonstration of
the window's coordinate system. The hope is that this will assist in
gaining an intuition for nannou's window coordinates.

Add a new `examples/basics/window_coordinates.rs` example

---

nannou/src/color/mod.rs
nannou/src/prelude.rs

This is a rebase of @linusbeff's work in #413. Thanks again!
Closes #413

Add `Rgb8` and `Rgba8` types

---

examples/Cargo.toml
generative_design/Cargo.toml
guide/book_tests/Cargo.toml
guide/src/changelog.md
guide/src/why_nannou.md
nannou/Cargo.toml
nannou/src/window.rs
nannou_audio/Cargo.toml
nannou_isf/Cargo.toml
nannou_laser/Cargo.toml
nannou_new/Cargo.toml
nannou_osc/Cargo.toml
nannou_package/Cargo.toml
nannou_timeline/Cargo.toml
nature_of_code/Cargo.toml

Be sure to check out the updated changelog within the guide for more details on everything included in this release!
We'll do a proper announcement post soon, but thought there was no harm in publishing in the meantime :)
*Disclaimer: This is the first time trying the automated `set_version` script and crate publishing via CI! Hopefully it works :crossed_fingers:*
Also closes #526.

Publish 0.14.0! Includes Draw overhaul, WPGU API improvements, LASER improvements and much more

---

examples/Cargo.toml
generative_design/Cargo.toml
guide/src/changelog.md
nannou/Cargo.toml
nannou/src/app.rs
nannou/src/draw/mod.rs
nannou/src/draw/renderer/mod.rs
nannou_laser/Cargo.toml
nature_of_code/Cargo.toml

See the commit messages and changelog diff below for more details!
Closes #584.

Fix `draw::Renderer` initialisation. Update changelog. Publish 0.14.1 with recent patches.

---

nannou/src/draw/renderer/mod.rs

This fixes a bug where the draw render pass would occasionally attempt
to generate a draw command with a bind group and render pipeline that
refer to separate yet identical bind group layouts.
Closes #612.

Separate bind group layout creation from render pipeline creation

---

guide/src/getting_started/create_a_project.md

Now this bare minimum example should compile and run without error ;-)

Update `Create a Project` example to use nannou version 0.14

---

guide/src/tutorials/draw/animating-a-circle.md
guide/src/tutorials/osc/osc-sender.md

Just a quick change so the url works correctly in the guide site.

Fix broken urls

---

nature_of_code/chp_06_agents/6_01_seek.rs
nature_of_code/chp_06_agents/6_01_seek_trail.rs
nature_of_code/chp_06_agents/6_02_arrive.rs
nature_of_code/chp_06_agents/6_03_stay_within_walls.rs
nature_of_code/chp_06_agents/6_03_stay_within_walls_trail.rs

fixed incorrect orientation issue in NOC chapter 6 examples

---

nannou/src/draw/renderer/mod.rs

Renderer::encode_render_pass no longer panics when given an empty Draw. Previously, it would attempt to create empty buffers, which is asserted to be false in wgpu::Device::create_buffer_mapped.

Fix empty mesh panic

---

generative_design/color/p_1_2_2_01.rs

Fix p 1 2 2 01.rs

---

generative_design/shape/p_2_1_1_01.rs

Fix p_2_1_1_01.rs drawing black lines on black background

---

examples/Cargo.toml
examples/audio/feedback.rs

I simply tried to port CPAL's feedback example to nannou. Related to issue #435.

Audio feedback example

---

guide/src/why_nannou.md

Also added explanation that midir can be used for the same purpose.
Related to #315

Guide: Unchecked MIDI support

---

examples/audio/hrtf-noise.rs

Hello! That's for this delightful project!
I think this was accidentally copied from the other example, so I've removed it.
Cheers,
Louis

Remove incorrect comment

---

nannou/src/app.rs

Add a method to quit the application

---

nannou/src/app.rs
nannou/src/wgpu/texture/mod.rs
nannou/src/window.rs

This is @danwilhelm's awesome work from #720 with a couple small amendments.
Dan, let me know if there are any issues with these amendments and we can address them in a follow-up PR! I'm about to try updating nannou to 0.7 but thought it would be nice to land this first.
Closes #676
Closes #690 
Closes #491 
Closes #651
Closes #720

Fix various resize crashes, texture memory leak [danwilhelm's PR #720 patched]

---

nannou/src/draw/primitive/text.rs

Fix #744
Uses `text.line_infos()` to skip glyph colors corresponding to non-rendered characters.
More code than I hoped, but takes advantage of `Info`s being ordered by ascending character position.
I did try a two-liner solution (~included in the comments), but it isn't efficient when many lines are rendered. Any suggestions for a more concise solution would be appreciated!

Fix `glyph_colors` miscoloring on resize

---

nannou/src/io.rs

This fixes a couple of issues. Previously, it was possible that the
written contents were not yet fully synchronised with the temporary file
on disk before the tmp file was renamed to the new file. We now ensure
that this synchronisation is performed and return an error if it fails
for some reason.
Previously, we removed the original file before replacing it with the
temporary file. This meant that data could be lost if an error occurred
while renaming the temporary file. Now, we rename the original to
`.backup`, then we replace it with the temporary file, and only after
replacement completes successfully do we delete the `.backup` file.

Improve `safe_file_save` behaviour, address some edge cases

---

nannou/src/state.rs

Refactor state::mouse::ButtonMap to use HashMap instead of array

---

examples/nannou_basics/all_functions.rs
examples/offline/tree.rs
examples/rust_basics/1_nannou_events.rs
guide/src/changelog.md
nannou/src/app.rs
nannou/src/event.rs
nannou/src/window.rs

Adding a "simplified" event, as well as a handler function for receiving the character value of a pressed keyboard key.
This PR resolves #480.

Received character keyboard event

---

nannou/Cargo.toml
nannou/src/app.rs
nannou/src/window.rs
nannou_conrod/Cargo.toml
nannou_timeline/Cargo.toml
nannou_wgpu/Cargo.toml
nannou_wgpu/src/lib.rs

Much smaller update than previous wgpu updates, see the 0.11 changelog:
https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md#wgpu-011-2021-10-07

Update from wgpu 0.10 to 0.11

---

README.md

File was moved in https://github.com/nannou-org/nannou/commit/25f92acc3067710ec8a2ec0cb5fa869d78b80370

Fix example link in README

---

nannou_wgpu/src/lib.rs

Fixes a small typo in nannou_wgpu

TextueSnapshot -> TextureSnapshot

---

guide/src/getting_started/create_a_project.md

This is a bit of a silly PR but that missing space triggered me somehow.

add missing space in guide sample main.rs

---

bevy_nannou_derive/src/lib.rs

fix: change `bevy_nannou_derive` to only expect the presence of `bevy_nannou`, not the `nannou` crate
